### ISSUE TITLE
Cleanup/remedidate large number of pubmed publications created in May 9 and 13 2019 harvests

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#1057]
PR that has a rake task to purge these publications here: #1058 
Underlying issue ticket: #1059

Since we deployed code that was merged on May 6-7 (v3.2.4 and v3.2.5) there were lots and lots of new publications being created with harvests, which seems very wrong.

```
Contribution.where('created_at > ?','2019-05-14').size
=> 73777

Publication.where('created_at > ?','2019-05-14').size
=> 73000
```

With nearly all of these being "pubmed" provenance (and likely from the pubmed harvester).  You can tell where publications came from by examining the pub_hash[:provenance] attribute in the each row (yes, you need to iterate, its not a top level model attribute).  If the associated contribution has a status of `new`, it likely came from a harvest (since manually entered publications are automatically are set to status of `approved`).

```
Contribution.where('created_at > ? and status=? and visibility=?',Time.parse('05-05-2019'),'new','private').size
=> 218937
```

**Comment by peetucket** [comment]
Not sure how to fix this data, as rolling back the database will destroy manual publication entries too that occurred during this time.  Could possibly:

1. Look at all new contributions created since May 6 with a status of 'new' and visibility of 'private'.
2. Grab all publication IDs.
3. For any new publications with these IDs that were also created since May 6, destroy the publication. 
4. For those publications created earlier, just destroy the contribution, but update the publication's pub_hash

**Comment by peetucket** [comment]
How to find authors with lots of new publications in a certain timeframe:

```
cutoff_pubs = 200 # more than this number of new pubs is a problem
start_timeframe = Time.parse('April 25 2019')
end_timeframe = Time.parase('May 14 2019')

authors = Contribution.where('status = ? and visibility = ? and created_at > ? and created_at < ?', 'new', 'private', start_timeframe, end_timeframe).pluck(:author_id).uniq;nil

author_info = []
authors.each do |author_id|
  author = Author.find(author_id)
  new_pubs = author.contributions.where('status = ? and visibility = ? and created_at > ? and created_at < ?', 'new', 'private', start_timeframe, end_timeframe).size
  if new_pubs > cutoff_pubs
     author_info << {cap_profile_id: author.cap_profile_id,name:"#{author.last_name}, #{author.first_name}",new_pubs:new_pubs,num_authors_with_same_initial:num_authors_with_same_initial}
  end
end;nil
```

**Comment by justinlittman** [comment]
Authors with the most publications:
```
Contribution.group(:author_id).order('count_id desc').count('id').take(10)
=> [[49036, 96382],
 [119413, 42466],
 [121822, 42463],
 [37959, 42458],
 [124862, 8614],
 [946, 4909],
 [7522, 4262],
 [29230, 2842],
 [124527, 2363],
 [21, 2323]]
```
Guessing it is the first 4 that are our problems.

**Comment by justinlittman** [comment]
Looking through the logs for author 49036:
```
[pub@sul-pub-prod log]$ gunzip -c pubmed.log-*.gz | grep "author 49036"
I, [2019-05-10T02:05:50.802790 #26454]  INFO -- : Pubmed::Harvester - author 49036 - processing author 49036
I, [2019-05-10T02:05:52.626740 #26454]  INFO -- : Pubmed::Harvester - author 49036 - 100000 pmids for search
I, [2019-05-10T02:17:52.841151 #26454]  INFO -- : Pubmed::Harvester - author 49036 - 94536 pmids without existing contributions
I, [2019-05-13T22:04:31.047274 #31901]  INFO -- : Pubmed::Harvester - author 49036 - processing author 49036
I, [2019-05-13T22:04:32.856436 #31901]  INFO -- : Pubmed::Harvester - author 49036 - 100000 pmids for search
I, [2019-05-13T22:36:12.916829 #31901]  INFO -- : Pubmed::Harvester - author 49036 - 76422 pmids without existing contributions
```

Logs are available ~ 20190509 to present.

**Comment by peetucket** [comment]
cool query, i think we need to restrict to just 'new' contributions though (since anything else has been acted upon with an approval or denial and we don't want to touch) and we can even restrict by date:

```
Contribution.where(status: 'new', visibility: 'private').where('created_at > ?',Time.parse('April 25 2019')).group(:author_id).order('count_id desc').count('id').take(10)

=> [[49036, 95143],
 [121822, 41375],
 [119413, 41362],
 [37959, 41353],
 [124527, 1965],
 [124862, 815],
 [29230, 809],
 [118528, 520],
 [29343, 454],
 [58860, 399]]
```

**Comment by justinlittman** [comment]
The reason this was spread over multiple days, I think, is because the number of results for a single query was capped at 100,000.

And it looks like an error occurred midway on the first run:
```
E, [2019-05-10T04:32:08.336998 #26454] ERROR -- : Pubmed::Client: Faraday::TimeoutError during PubMed Fetch API call
E, [2019-05-10T04:32:08.337082 #26454] ERROR -- : #<Faraday::TimeoutError wrapped=#<HTTPClient::ReceiveTimeoutError: execution expired>>
E, [2019-05-10T04:32:08.337175 #26454] ERROR -- : /usr/local/rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/openssl/buffering.rb:57:in `sysread'
```

**Comment by peetucket** [comment]
Publication IDs that were deleted (sul_pub_ids)
All of them created between April 25 and May 17

[cleanup_remove_new_contributions.log](https://github.com/sul-dlss/sul_pub/files/3193642/cleanup_remove_new_contributions.log)
