### ISSUE TITLE
Determine why pubmed harvester is creating lots of publications

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#1059]
Related to #1057

**Comment by justinlittman** [comment]
The problem is with a handful of authors that have huge numbers of publications. For example:
```
[2019-05-10T01:19:19.911294 #26454]  INFO -- : Pubmed::Harvester - author 37959 - processed author 37959: 40984 new publications
```

Author 37959 is:
```
PRODUCTION [1] pry(main)> Author.find(37959)
=> #<Author:0x0000000008a7f438
 id: 37959,
 cap_profile_id: 49793,
 active_in_cap: true,
 sunetid: "willgiar",
 university_id: 9663902,
 email: "willgiar@stanford.edu",
 cap_first_name: "William",
 cap_last_name: "Giardino",
 cap_middle_name: "Joseph",
 official_first_name: "William",
 official_last_name: "Giardino",
 official_middle_name: "J",
 preferred_first_name: "William",
 preferred_last_name: "Giardino",
 preferred_middle_name: "Joseph",
 created_at: Wed, 16 Oct 2013 08:57:53 UTC +00:00,
 updated_at: Fri, 12 Sep 2014 11:35:04 UTC +00:00,
 california_physician_license: "",
 cap_import_enabled: true,
 emails_for_harvest: "willgiar@stanford.edu">
```

The pubmed query for this user is:
```
PRODUCTION [12] pry(main)> q.send(:term)
=> "((Giardino William[Author])) AND (Stanford University[Affiliation] OR Oregon Health & Science University[Affiliation] OR University of Washington[Affiliation])"
```

Notice the *&*.

Querying with the & is interpreted as:
```
"Giardino, William[Full Author Name] AND Stanford University[Affiliation] OR ((\"oregon\"[MeSH Terms] OR \"oregon\"[All Fields]) AND (\"health\"[MeSH Terms] OR \"health\"[All Fields]))"
```
and has 42,710 results.

Querying without the & is interpreted as:
```

**Comment by justinlittman** [comment]
Here are the pubmed ids that are in the query without & but not in the query with and:
* 23398267
* 22444954
* 22046429
* 21833501

and the reverse:
* 22347848

Looking at the articles in Pubmed, the difference seems to be whether and is used or & is used.
![Screen Shot 2019-05-16 at 7 41 36 AM](https://user-images.githubusercontent.com/588335/57851279-262cdd00-77ae-11e9-80df-dfa474272f06.png)

![Screen Shot 2019-05-16 at 7 42 40 AM](https://user-images.githubusercontent.com/588335/57851304-36dd5300-77ae-11e9-9f13-79d690422381.png)

**Comment by justinlittman** [comment]
So the proposed solution would be when an affiliation name has an &, search on it without the & and with the & replaced with and.
