### ISSUE TITLE
Improve error messaging reported to Honeybadger

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#1150]
This exception reported an interesting and useful error from our code, but the actual message was buried in the "context" and easy to miss.  Can we put this in a more noticeable message to honeybadger? 

HB error: https://app.honeybadger.io/projects/50046/faults/49773157

The place in the code reporting it: https://github.com/sul-dlss/sul_pub/blob/master/lib/notification_manager.rb#L28-L30

**Comment by jmartin-sul** [comment]
a bit more from the honeybadger alert, in case it takes us longer than our HB account's retention period to look into this issue:


<img width="1137" alt="Screen Shot 2020-03-19 at 6 37 09 PM" src="https://user-images.githubusercontent.com/7741604/77129341-eb6c8480-6a10-11ea-89ed-ab3812cc8d9e.png">
<img width="1153" alt="Screen Shot 2020-03-19 at 6 37 26 PM" src="https://user-images.githubusercontent.com/7741604/77129342-ee677500-6a10-11ea-864f-142832556e2d.png">
<img width="1137" alt="Screen Shot 2020-03-19 at 6 37 55 PM" src="https://user-images.githubusercontent.com/7741604/77129343-ef000b80-6a10-11ea-910f-83a7d608259d.png">

**Comment by peetucket** [comment]
closed by #1153
