### ISSUE TITLE
monitoring framework: Switch from is_it_working to okcomputer and split checks

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#119]
We need to monitor two things:
1. Are the parts of our application that are under our immediate control operational (e.g. the app is running, the database is up, solr is up).  
2. Are all of the external dependencies working (e.g. the CAP API, ScienceWire API, PubMed).

Currently is_it_working monitors both.  What we want to do is have Nagios/OpsGenie alert only one 1 above (since this is what we can actually act on), while having a second monitoring system (HoneyBadger?) send email alerts to the team on 2 above (since it is still useful to know and may trigger an email or investigation on why the API call is not working).

**Comment by drh-stanford** [comment]
also see https://github.com/sul-dlss/devops-concerns/issues/90

**Comment by drh-stanford** [comment]
also:

4. `/status/abc.json` for a critical aspect which goes to ops

**Comment by drh-stanford** [comment]
everything is done here except #132.

**Comment by drh-stanford** [comment]
So, `CapHttpClient` is very aggressive about sending Honeybadger notifications. Our intent is that when monitoring of `/status/external-CapHttpClient` fails, that we get email to `sul-cap-team` via Nagios. But we're getting both email there and a notification from Honeybadger. 

To support that scenario in the code we need some way to disable Honeybager during a monitoring request only.

**Comment by drh-stanford** [comment]
I'm thinking that we should probably use cron to do the monitoring of the external services. We're finding that the aggressive nagios checks is proving to cause a lot of exceptions as the external services are up-and-down evidently. to do this we need to figure out _when_ we actually need the external services (e.g., before a ScienceWire harvest) and do the monitoring at that point. That also raises the question of whether we should abort the process if the monitoring fails.

**Comment by drh-stanford** [comment]
From Slack discussion from @eefahy :

> 1. is the service available when the app attempts to accomplish a task
> 2. how often does the service disappear from the app

> no 1. should be done programmatically from the app IMHO
> no 2. should/can be done via monitoring
