### ISSUE TITLE
monitoring framework: Update devops documentation for sul_pub when master goes into production

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#120]

**Comment by drh-stanford** [comment]
These docs exist here: https://github.com/sul-dlss/DevOpsDocs/tree/master/projects/sul_pub but they are likely not complete.

**Comment by drh-stanford** [comment]
The DevOpsDocs are current for our production deployment, but not for the `master` branch. We will need to revise them when we take `master` into production
