### ISSUE TITLE
Create cron scheduling for updating ORCID in prod

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/sul_pub#1263]
There is a rake task that wraps all of thee tasks.  Enable that rake task in schedule.rb for production for every 3 days:

1. Retrieve the current list of all SUNETID, ORCID ID, ORCID token, and permission type from UIT API.
2. Replace all existing author ORCID IDs with those just retrieved.
3. Post new publications.

**Comment by peetucket** [comment]
how is this different from #1296?

Or we saying this will create a new task to wrap the MaiS and the ORCID updates into one rake task that will scheduled instead of two individual ones that will exist from #1296

**Comment by peetucket** [comment]
Closed in favor of #1296
