### ISSUE TITLE
Clean up shared_config branches

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/sul_pub#1278]
The abundance of legacy shared_config branches are confusing.

![image](https://user-images.githubusercontent.com/588335/117967126-b39a5d80-b2f2-11eb-8c5f-d882d84c2b06.png)

Please remove unused branches and ideally rename existing to match environments.

**Comment by peetucket** [comment]
Deleted `sub-pub-dev-solo`, `petucket-sul-pub-cap-dev` and `sul-pub-cap-dev`, all of which are no longer needed.

That leaves the four shared configs that map to the four existing deploy environments, plus one called `sul-pub-laptop`  This was intended to serve as a basis for local development, but in order not to maintain another branch, we can also delete this and update the readme as shown in #1280 to tell developers to just copy the dev version instead.

**Comment by justinlittman** [comment]
That makes sense to me and is consistent with other projects.
