### ISSUE TITLE
Create cron scheduling for adding publications to ORCID

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/sul_pub#1296]
[HOLD] after some more testing is complete, we can enabled in prod

Let's say every 3 days.

Note, all we have to do is add the harvester_prod role to the existing scheduled task added in #1351

**Comment by peetucket** [comment]
Should be enabled in `schedule.rb` for the ` rake 'orcid:add_all_works'` task on Monday June 21 followed up an immediate manual run.  We then need to notify Tina.

Run manually the first time and monitor.  Best done in screen as it will take a while:

`RAILS_ENV=production bundle exec rake orcid:add_all_works`
