### ISSUE TITLE
Verify create a work ORCID API endpoint

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#1300]
Verify that we can create a work on an ORCID profile using the API, not necessarily using the full mapping yet.

Make use of ORCID API client

**Comment by justinlittman** [comment]
Mission accomplished. Here's the proof: https://github.com/sul-dlss/sul_pub/blob/main/fixtures/vcr_cassettes/Orcid_Client/_add_work/adds_work.yml
