### ISSUE TITLE
Testing and validation plan

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#1343]
Testing plan below, with what we are testing and the basic process.  Add feedback as comments to this ticket.  We will generate new tickets for resulting work.

### What we are testing:

- [ ] Spot check publications that have been pushed from Profiles to ORCID to see if they look "ok".  Purpose is to validate data mapping.  We have done this, Jacob asked for other volunteers to spot-check.
- [ ] Ensure we get users who have newly connected their SUNET with the Sandbox ORCID in UAT back via the MAIS API.  Purpose is to validate the MAIS API is returning new users as they are connected.   see #1348
- [x] Ensure we do not get duplicate publications when pushing publications multiple times for the same user.  Purpose is to ensure we do not push the same publications more than once.
- [x] Ensure we get a new publication when when pushing publications again for the same user that has had a new publication added to Profiles since the last time we pushed.  Purpose is to validate that new publications are being discovered and added.
- [x] Ensure that users with many publications (many hundreds) work correctly.  Purpose is to validate that paging, etc. works with the APIs and that performance is not an issue.

Spreadsheet of users: https://docs.google.com/spreadsheets/d/1EZgXOLK6W7rY-0HFUa6Szasr82EeFMzU7S_Gb2rQmsM/edit

### How:

**Spot checking:**

Get ORCID accounts with test publications for spot checking:

* Pete's Sandbox ORCID account: https://sandbox.orcid.org/0000-0002-2230-4756 | https://profiles-u02.stanford.edu/russ-altman?tab=publications
* Jacob's Sandbox ORCID account: https://sandbox.orcid.org/0000-0002-7262-6251  | https://profiles-u02.stanford.edu/intranet/stephen-boyd?tab=publications
* Ask people (Jacob, Peter, Justin, John, Vivian, Arcadia, Grace and Zach) to review the profile and compare to the ORCID account just to verify publications look similar.  NOTE: The publications are coming from actual stanford researchers even though they haven't specifically linked to a Sandbox ORCID account.  Each user will have many more publications in their Profile than in the ORCID account because many publications in Profiles do not have identifiers (e.g. DOI, PMID) that are required for pushing to ORCID.

**Other tests**: 

For dupe and new publication adding checking and ensuring new users are added:

* Use Karen's account (https://sandbox.orcid.org/0000-0002-7372-3555) for testing dupes and new publications.
* Use rake task to delete existing ORCID publications (orcid:delete_author_works) for that user
  * `RAILS_ENV=production bin/rake orcid:delete_author_works['<SUNETID>']`
* Verify that the ORCID profile does not have any works
* Verify in the rails console the user does not have any contributions with ORCID put codes
  *  `author = Author.find_by(sunetid: '<SUNETID>'); Contribution.where(author_id: author.id).where.not(orcid_put_code: nil).count # should be zero`
* Unauthorize stanford in ORCID
* Run rake task (orcid:add_author_works) and expect it to fail due to no authorization at ORCID
* Authorize stanford in ORCID
* Run rake task (orcid:add_author_works) and expect it to succeed and add publications to ORCID.  Get count of publications in ORCID.
  * `RAILS_ENV=production bin/rake orcid:add_author_works['<SUNETID>']`
* Verify in the rails console that the user has contributions with ORCID put codes and the count should be the same or slightly bigger than what is in ORCID.
  * `author = Author.find_by(sunetid: '<SUNETID>'); Contribution.where(author_id: author.id).where.not(orcid_put_code: nil).count`
* Add a new publication to Karen's UAT Stanford profile by associating a new contribution with an existing publication (doesn't have to be hers)
  * can pick a random `Publication`, create a new `Contribution`, and associate the `Contribution` to the `Publication` and our test `Author`.  @peetucket notes we may have to fill in some more details on the `Contribution`, and that there are likely some helper methods to do that for us?
* Run rake task (orcid:add_author_works) and expect it to succeed and add one new publication to ORCID.  Get count of publications in ORCID and expect it to be exactly one bigger than before.
  * linux console: `RAILS_ENV=production bin/rake orcid:add_author_works['<SUNETID>']`
  * rails console: `author = Author.find_by(sunetid: '<SUNETID>'); Contribution.where(author_id: author.id).where.not(orcid_put_code: nil).count`
* Pick a different Humanities faculty member and push their publications to a free Sandbox ORCID account.

**Comment by jmartin-sul** [comment]
@peetucket, @justinlittman, and i ran through the "Other tests" plan outlined in the description on `cap-dev` this morning, and all worked as expected.  one caveat: we didn't get to the "Pick a different Humanities faculty member and push their publications to a free Sandbox ORCID account."

iirc, the worry with humanities publications is that we may not be able to map them at the same rate of success as our mapping of scientific publications?

**Comment by peetucket** [comment]
Yes, the concern with humanities faculty is that their publications are sufficiently different than scientific fields that it would be nice to see how they map to validate any differences.

**Comment by peetucket** [comment]
New plan: we are going to do this live by having Zach find a couple faculty members that we will push to their actual ORCID once they've made the authorization in prod.  We will leave the schedule off until we validate this.
