### ISSUE TITLE
Create ORCID wiki helper page

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/sul_pub#1347]
Started here: https://github.com/sul-dlss/sul_pub/wiki/Useful-console-commands-(ORCID,-MaIS)

Containing common commands and/or troubleshooting.  Add a new wiki page similar to this one: https://github.com/sul-dlss/sul_pub/wiki/Useful-console-commands-(harvest,-WoS,-Pubmed,-others)  and add link to the sidebar for ease of navigation

What to add:

- [x] look up which publications for a given author have already been pushed to ORCID (i.e. contributions with a non-nil put code)
- [x] deleting author works on orcid for a given sunet (and why you want to do this, i.e. not a normal thing to do) (rake task)
- [x] sending author works to ORCID for a given sunet (rake task)

**Comment by peetucket** [comment]
I'm going to call this closed ... let's just add commands as they become useful to this page.
