### ISSUE TITLE
figure out our release branches and how to push new code to production

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/sul_pub#137]
There's currently some confusion about the branches and which ones were deployed, and more importantly, which branches should we use for pushing new changes to production...

for production:
```
Branch prod-dns-switchover (at f5d4f58) deployed as release 20160512033754 by azanella
```

for CAP-QA:
```
Branch master (at 1c44be2) deployed as release 20160715183440 by dlweber
```

for CAP-Dev
```
Branch master (at 1c44be2) deployed as release 20160715183325 by dlweber
```

for dev:
```
Branch master (at 1c44be2) deployed as release 20160715183554 by dlweber
```

Branches:

- There is a `2.x-release` branch that isn't deployed: `d9aeeeb  on Jun 8`. It currently has version `v2.0.0.rc3`. But it is `11 commits ahead, 30 commits behind master.`
- There is a `master` which is deployed: `Latest commit 1c44be2  on Jul 12`. That is the one that is deployed.
- There is a `prod-dns-switchover` branch: `Latest commit 798815b  on Apr 13`. It is deployed to production (and is 400+ commits behind master).

So, the actions are what?

- [ ] Rename `prod-dns-switchover` to `1.x-release` and then use that branch to push fixes to current production? OR
- [ ] Create a new `1.x-release` branch off of `f5d4f58` and leave `prod-dns-switchover` as-is?

AND

- [ ] Delete `2.x-release` since we're not using it and instead using the tip of `master` for CAP-QA/Dev deploys? What are the implications of this??? Will we lose commits?

@tallenaz @peetucket here's a ticket for our current challenge with the release process for pushing new releases to production.

**Comment by peetucket** [comment]
1. Comparing 2.x to master --- no actual changes (just the version file).    https://github.com/sul-dlss/sul_pub/compare/2.x-release

I recommend deleting 2.x-release branch and using master in the way we normally expect (latest code that is tagged before a deploy).

2. Because we can't deploy latest master to prod, I like the idea of having the branch deployed to prod be a "1.x-release".  Where is the f5d4f58 deploy in the history of the current prod-dns-switchover?

**Comment by drh-stanford** [comment]
That's a very good question -- I cannot find `f5d4f58` on that branch -- it must have been rebased?

**Comment by drh-stanford** [comment]
^^^maybe it was deployed from a different repo? Didn't we switch to a new repo at some point?

**Comment by drh-stanford** [comment]
Ok, it looks like all of the SHAs were recomputed when we did the switchover. So,

As far as I can tell, `798815b996df1590efcadcbcc7956cedee1b5faf` in `sul_pub` is the same as `f5d4f58a04eb3ce28b023aa3bf4fa146de42f664` in `sul-pub`. That is the tip of the `prod-dns-switchover` branch, so effectively (assuming these 2 SHAs are really the same code) that is the deployed version even though the SHA doesn't match.

**Comment by peetucket** [comment]
Excellent. So then I think this leads to the second recommendation, which is a rename of prod-dns-switchover to make it clearer that is what is deployed in production now.

Any pull requests that get merged to master that we also want in -prod now would get cherry-picked onto that branch.

**Comment by drh-stanford** [comment]
It looks like a copy and delete is the only way to "rename" a branch on a remote server. It looks like the procedure is this:

```
git checkout prod-dns-switchover
git branch --move 1.x-release
git push origin 1.x-release
git push origin :prod-dns-switchover  # the colon deletes the remote branch
```

**Comment by drh-stanford** [comment]
I've renamed the branch to `1.x-release` and I've deleted the `2.x-release` branch.
