### ISSUE TITLE
[sul_pub/prod] ORCID.org API returned 400 

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/sul_pub#1383]
```({"response-code":400,"developer-message":"400 Bad request: invalid JSON - cvc-maxLength-valid: Value 'DISCLOSURES: Sharman: AbbVie: Consultancy, Honoraria, Research Funding; Genentech: Consultancy, Honoraria, Research Funding; TG Therapeutics: Consultancy, Honoraria, Research Funding; Pharmacyclics LLC, an AbbVie Company: Consultancy, Honoraria, Research Funding; Acerta: Consultancy, Honoraria, Research Funding; AstraZeneca: Consultancy, Honoraria,...
```

## Backtrace

    line 40 of [PROJECT_ROOT]/lib/orcid/client.rb: add_work
    line 41 of [PROJECT_ROOT]/lib/orcid/add_works.rb: add_work
    line 30 of [PROJECT_ROOT]/lib/orcid/add_works.rb: block in add_for_orcid_user

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/50046/faults/80045843)

**Comment by jmartin-sul** [comment]
in case i don't get to this before my FR shift is over today: justin suspects that we just need to figure out the size limit for this field in the ORCID API, and then truncate at that length before we send a value over.
