### ISSUE TITLE
Backfill Pubmed publication dates in production

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#1475]
HOLD until the recently merged #1473 is deployed to production.  Then can do this task (but only necessary in production).

We need to use the new code to "back-fill" publication dates in any previous Pubmed publications.  This has already been done in the -dev, -stage, and -qa environments, so it only needs to be done in production.

To do this, after #1473 is deployed, go to the production rails console and use the sets of commands below, which will iterate over Pubmed sourced publications and "rebuild" the data structure in the database to include the new date.  This new date will then be picked up the following evening with the Profiles team runs their nightly update.  Iterating below over the ~18k records will take about 15 minutes, so you might want to run it in a screen on the box just in case your ssh session gets disconnected mid-way.  If it does get interrupted, it should be safe to re-run though, as it is not destructive.

```
cap prod ssh

# may want to start a screen here...

bundle exec rails c -e p

updated = 0
date_added = 0
num_pubs = Publication.where(sciencewire_id: nil, wos_uid: nil).where('pmid IS NOT ?', nil).count
puts "Found #{num_pubs} likely Pubmed provenance"
Publication.where(sciencewire_id: nil, wos_uid: nil).where('pmid IS NOT ?', nil).find_each.with_index do |pub, i|
  puts "#{i+1} of #{num_pubs} : #{pub.pub_hash[:provenance]}"  
  next unless pub.pubmed_pub? # guard against this not actually be a pubmed provenance
  next unless pub.pub_hash[:date].blank? # only need to remap if the date is blank, note comment this out if you need to fix dates
  pub.rebuild_pub_hash
  updated += 1
  date_added +=1 unless pub.pub_hash[:date].blank?
end;
puts "Total pubs: #{num_pubs}; updated: #{updated}; added date: #{date_added}"
```

**Comment by lwrubel** [comment]
Got the following: `Total pubs: 17984; updated: 17983; added date: 17983`.

**Comment by peetucket** [comment]
I did a sweep through all of the Pubmed provenance pubs and couldn't find any with a blank date, so not sure what happened there with the counts.  I think we can call this done.
