### ISSUE TITLE
ORCID API bad JSON created on pushing publication

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/sul_pub#1478]
## Backtrace

    line 83 of [PROJECT_ROOT]/lib/orcid/client.rb: add_work
    line 41 of [PROJECT_ROOT]/lib/orcid/add_works.rb: add_work
    line 30 of [PROJECT_ROOT]/lib/orcid/add_works.rb: block in add_for_orcid_user

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/50046/faults/84341000)

**Comment by peetucket** [comment]
Find an example publication triggering the error:

- Look at the JSON sent and find an identifier (e.g. DOI)
- Search for the identifier in our database and locate the publication ID

Look at one instance of the exception, found this DOI: `10.2514/6.2005-4375`

```
pi = PublicationIdentifier.where(identifier_value:'10.2514/6.2005-4375')
p = Publication.find(pi.first.publication_id)

p.pub_hash[:provenance] 
=> "cap" # this is a manually entered publication from the UI, i.e. not harvested from WoS or Pubmed
```

The exception from ORCID appears to be complaining about a non-allowed blank string value somewhere, let's look at the pub-hash to see if anything jumps out

```
p.pub_hash
```

Looks like there is a totally blank author, this is probably the issue (somewhat entered it blank and we just recorded it that way).

```
p.pub_hash[:author].last
=> {"name"=>"  ",
 "alternate"=>[],
 "lastname"=>"",
 "firstname"=>"",
 "middlename"=>"",
 "role"=>"author",
 "additionalProperties"=>{}}
```

Here is the mapped version we sent to the ORCID API:

```
Orcid::PubMapper.map(p.pub_hash)

....
     {:"contributor-orcid"=>nil,
      :"credit-name"=>{:value=>""},
      :"contributor-email"=>nil,
      :"contributor-attributes"=>
       {:"contributor-sequence"=>nil, :"contributor-role"=>"author"}}]},
....
```

Likely we need to strip that last contributor where the name value is blank.

**Comment by peetucket** [comment]
I think the class we need to change is the `ORCID::PubAuthorMapper` so it just rejects blank authors instead of trying to map them:

```
Orcid::PubAuthorMapper.map(p.pub_hash[:author].last)
=> {:"contributor-orcid"=>nil,
 :"credit-name"=>{:value=>""},
 :"contributor-email"=>nil,
 :"contributor-attributes"=>
  {:"contributor-sequence"=>nil, :"contributor-role"=>"author"}}
```

**Comment by peetucket** [comment]
Find the author this example problematic publication is associated with:

```
c = Contribution.where(publication_id: p.id)
c.first.author
=> #<Author:0x00000000077ea728
 id: 3388,
 cap_profile_id: 9636
....
```
