### ISSUE TITLE
Bug in cap_http_client.rb:28:in `generate_token`

### ISSUE THREAD

**Issue by dazza-codes** [sul-dlss/sul_pub#148]
Error detected in: CAP (cap-qa)

Full report at https://app.honeybadger.io/projects/50046/faults/31721385

SocketError: Failed to open TCP connection to authz.stanford.edu:443 (getaddrinfo: Temporary failure in name resolution)

Summary

ok_computer/ok_computer#show

URL: https://sul-pub-cap-qa/status/external-CapHttpClient

Hostname: sul-pub-cap-qa.stanford.edu
Context

    message: CapHttpClient: SocketError during CAP request

Trace

lib/cap_http_client.rb:28:in `generate_token`
lib/cap_http_client.rb:68:in `make_cap_request`
lib/cap_http_client.rb:51:in `get_auth_profile`

**Comment by drh-stanford** [comment]
this looks like a DNS failure to our authentication server in general IT.

**Comment by darrenleeweber** [comment]
Should be have some change in the retries for this exception (`SocketError`)?  That is, should the retry count be larger or add an exponential function to a retry delay period between tries?  If it's an occasional DNS failure for that Stanford endpoint that often resolves itself, it might pay to change the retry details to avoid the same HB notifications all the time.

There's also some analysis that might be done on how the cap polling loop handles exceptions in the client like this.  That is, if it needs to poll for 100's of profiles and every one of them hits the same exception (when instantiating a new client), there might be some alteration of that logic?
