### ISSUE TITLE
[CAP/production] JSON::ParserError: <title>CAP Network Maintenance : Stanford University</title>

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/sul_pub#154]
## Backtrace

    line 85 of [PROJECT_ROOT]/lib/cap_http_client.rb: block in make_cap_request
    line 71 of [PROJECT_ROOT]/lib/cap_http_client.rb: times
    line 71 of [PROJECT_ROOT]/lib/cap_http_client.rb: make_cap_request

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/50046/faults/31983583)

**Comment by darrenleeweber** [comment]
The SUL-CAP system could detect when the CAP-API is in a maintenance state and halt operations that interact with the CAP-API.  At the least, the cap authors poller or authorship interactions should handle this exception.
