### ISSUE TITLE
Ignore pubmed queries for names that produce bad queries

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#1546]
If the author's name contains certain boolean operators, Pubmed will incorrectly parse the query and return too many results.  (e.g. "Or" is a male Hebrew name)

Results of investigation, showing basically all of this user's publications from Pubmed:

```
author=Author.find_by(sunetid:'orzolty')
author.publications.size
=> 1151
author_query = Pubmed::QueryAuthor.new(author)
author_query.send(:term)
=> "((Zolty, Or[Author])) AND (Stanford University[Affiliation])"
pmids_from_query = query.pmids;
pmids_from_query.size
=> 1153
```

If you go the Pubmed web interface, you will see how Pubmed is parsing this query:

https://www.ncbi.nlm.nih.gov/pmc/?term=((Zolty%2C+Or%5BAuthor%5D))+AND+(Stanford+University%5BAffiliation%5D)

Bottom line is that Pubmed is turning it into this: `(Zolty[All Fields] OR Author[All Fields]) AND Stanford University[Affiliation]` which is not correct.

We looked at the Pubmed API documentation and tried different variations of our query and couldn't produce the intended results.

We also looked at the WoS query, which does seem to produce the expected results and does not appear to have an issue, so relying on WoS seems sufficient for these edge case users.

Actions:
- [x] In the pubmed query class, we should indicate the query is invalid if any of the author's names contains a configured list of disallowed terms ("OR", "AND", "NOT"): https://github.com/sul-dlss/sul_pub/blob/main/lib/pubmed/query_author.rb#L22-L24
- [x] Double-check that the author now returns invalid 

```
author=Author.find_by(sunetid:'orzolty')
query_author = Pubmed::QueryAuthor.new(author)
query_author.valid? # should return false instead of true
```
- [x] check to see if we should set all of the 'new' status publications for this author to 'denied', or if the Profiles team (in the #sul-cap-colab channel) wants to do this on their end

Something like:
```
author.contributions.where(status:'new').each {|contrib| contrib.update(status: 'denied')}
```

- [x] Communicate with Profiles team about the issue, which is that Pubmed is incorrectly parsing queries when an author's name is "Or", "And", "Not" and we can't seem to figure out how to get their query syntax to understand.  Our recommendation and course of action is to **not** query Pubmed for these users, and to rely on the Web of Science only, which does seem to work fine.

- [x] Send a support request to NCI/Pubmed to ask about how to query correctly.

- [x] Investigate further remediation needed for other authors. We have 10 authors with the name "Or" and a subset have similarly large publication counts.

```
authors=Author.where(cap_last_name: ['or', 'and', 'not']).or(Author.where(cap_first_name: ['or', 'and', 'not']))
authors.size
=> 10
authors.each do |a|
  count = a.contributions.where(status:'new').count
  next if count == 0
  puts "#{a.sunetid} (#{a.cap_profile_id}) : #{a.cap_first_name} #{a.cap_last_name} : #{count}"
end;nil
=>
ogozani (6423) : Or Gozani : 172
orher (84143) : Or Hershkovits : 1196
ori1981 (304265) : Or Rabinowitz Batz : 1139
```

**Comment by lwrubel** [comment]
[] Investigate further remediation needed for other authors. We have 7(?) authors with the name "Or" and a subset have similarly large publication counts.

**Comment by peetucket** [comment]
Users that have one of these terms in first or last name: 

```
author=Author.where(cap_last_name: ['or', 'and', 'not']).or(Author.where(cap_first_name: ['or', 'and', 'not']))
author.size
=> 10
author.each {|a| puts "#{a.cap_first_name} #{a.cap_last_name} : #{a.publications.count}"};nil
Or Gozani : 886
Or Meir : 0
Or Hershkovits : 1199
Or Litany : 476
Chi Mong Christopher Or : 0
Chi Mong Or : 0
Or Keynan : 0
Johanna And : 0
Or Zolty : 1151
Or Rabinowitz Batz : 1147
```

**Comment by peetucket** [comment]
Note: After back and forth with NIH/NCI, there was no resolution to the Pubmed query issues and it is not clear if there will be.  I don't see a workaround with their current API to make it work.
