### ISSUE TITLE
Switch to WoS REST API : SOAP API sunset November 2023

### ISSUE THREAD

**Issue by edsu** [sul-dlss/sul_pub#1609]
@lwrubel noticed this alert in HoneyBadger:  https://app.honeybadger.io/projects/50046/faults/79686845

> Savon::SOAPFault: (soap:Server) The Web of Science SOAP API is scheduled to be sunset on November 1, 2023. All users must update their code to use the Web of Science REST API. For more details and help, see https://support.clarivate.com/ScientificandAcademicResearch/s/article/Web-of-Science-SOAP-API-Sunset-Frequently-asked-questions-FAQs?language=en_US.

**Comment by peetucket** [comment]
1. Example of where we have used the WoS REST client for RIALTO: 

https://github.com/sul-dlss-deprecated/rialto-etl/blob/main/lib/rialto/etl/service_client/web_of_science_client.rb

2. I have requested an API key for testing this API with sul_pub, but we have one for RIALTO already we can use for testing right now: https://github.com/sul-dlss/shared_configs/blob/rialto-etl-prod/config/settings/production.yml#L36-L37

3. We currently have two WoS clients in sul-pub:
- Links AMR, for fetching all possible identifiers for a given publication: https://github.com/sul-dlss/sul_pub/blob/main/lib/clarivate/links_client.rb
- WoS Expanded API, for general harvesting: https://github.com/sul-dlss/sul_pub/blob/main/lib/web_of_science/client.rb

The information on https://support.clarivate.com/ScientificandAcademicResearch/s/article/Web-of-Science-SOAP-API-Sunset-Frequently-asked-questions-FAQs?language=en_US above suggests the Links AMR is replaced with the WoS Starter API, but it may be possible that all of the info in that API is now available via the WoS Expanded API, and we can go down to a single client.  All of the identifiers were *not* available in the SOAP based WoS Expanded API, which led to the complication of having to use two clients.

4. Documentation for new API: 

Documentation for each API is available on the Developer Portal (https://developer.clarivate.com/). Navigate to the individual API page (linked below) and click ‘View swagger definition’ or ‘try it’ on the page to access the documentation. Schema and example responses are also available.
Expanded API: https://developer.clarivate.com/apis/wos
Starter API: https://developer.clarivate.com/apis/wos-starter
Lite API: https://developer.clarivate.com/apis/woslite

**Comment by peetucket** [comment]
@justinlittman added some info to this ticket about new API.
