### ISSUE TITLE
Testing strategies for switch to WoS REST API

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#1618]
In order to validate the work described in #1609 and in #1612, proposal is:

- go to prod, look at the harvest schedule in cron...pick the day after a harvest was run
- look at the total number of contributions added in the last day and fetch the WoS IDs.  The goal is to see what was added by the current code (SOAP API) harvest and then later compare to what was harvested by the new code in the same time period:

```
timeframe  =  Date.today - 1.day # look back 1 day
total_contributions_added = Contribution.where('created_at > ?',timeframe).where(status:'new').size;
wos_uids_added = Publication.where('created_at > ?',timeframe).pluck(:wos_uid).compact.size;
```

- run a full harvest with the new code on the qa server (cap-dev-a) and monitor HB and server logs for any errors
- wait for harvest to complete and then do the same thing:

```
timeframe  =  Date.today - 1.day # look back 1 day
total_contributions_added = Contribution.where('created_at > ?',timeframe).where(status:'new').size;
wos_uids_added = Publication.where('created_at > ?',timeframe).pluck(:wos_uid).compact.size;
```

- compare the total_contributions_added count and the wos_uids_added and see if the pass they sanity check .... i would expect them to be very similar, as the authors are very similar between prod and cap-dev-a and the harvest timeframes are very similar, only off by a day or so

Next steps:
- [x] deploy to UAT
- [x] inform #sul-cap-collab channel
- [x] percolate for a few weeks
- [x] merge this puppet change https://github.com/sul-dlss/puppet/pull/9661/files
- [x] set uat environment to use main puppet branch again (they were manually changed to use the puppet branch above)
- [x]  merge if no errors
- [x] add back in uat as a non-standard deploy environment to sdr-deploy so dependency updates go to UAT again, i.e. revert https://github.com/sul-dlss/sdr-deploy/pull/220
- [x] Go directly to #1619 and complete tasks there

**Comment by mjgiarlo** [comment]
- [ ] go to prod, look at the harvest schedule in cron...pick the day after a harvest was run
- [ ] look at the total number of contributions added in the last day and fetch the WoS IDs.  The goal is to see what was added by the current code (SOAP API) harvest and then later compare to what was harvested by the new code in the same time period:
    ```ruby
    timeframe  =  Date.today - 1.day # look back 1 day
    total_contributions_added = Contribution.where('created_at > ?',timeframe).where(status:'new').size;
    wos_uids_added = Publication.where('created_at > ?',timeframe).pluck(:wos_uid).compact
    ```
- [ ] run a full harvest with the new code on the qa server (cap-dev-a) and monitor HB and server logs for any errors
- [ ] wait for harvest to complete and then do the same thing:
    ```ruby
    timeframe  =  Date.today - 1.day # look back 1 day
    total_contributions_added = Contribution.where('created_at > 
    ?',timeframe).where(status:'new').size;
    wos_uids_added = Publication.where('created_at > ?',timeframe).pluck(:wos_uid).compact
    ```
- [ ] compare the total_contributions_added count and the wos_uids_added and see if the pass they sanity check .... i would expect them to be very similar, as the authors are very similar between prod and cap-dev-a and the harvest timeframes are very similar, only off by a day or so

**Comment by mjgiarlo** [comment]
@peetucket @justinlittman I did the above work but I'm not sure I did it right and I'm also not sure the results pass the sanity check. See my methodology and results above. I'll keep this assigned to me for now but I'm not sure what to do at the moment.
