### ISSUE TITLE
Analysis of work required to use new ScienceWire API

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#171]
Clarivate (the new company that provides the Web of Science/ScienceWire API) has updated their API and is requesing that we use it.  The new API documentation is attached, and it appears that 

1. There is a new authentication mechanism - you post a username/password to get an authentication key you use for a session.

2. The calls have a different data structure both for the request and the response.

3. The response no longer includes a PMID for publications.  There is a separate call to determine if a publication has a PMID (though you check multiple publications at once).  This implies we would have an extra call beyond what we do now.

We should do a bit more analysis to estimate the work needed to update sul_pub to work with the new API and to see if this would cause any problems with current functionality.

**Comment by peetucket** [comment]
updated API documentation: 

[WoSWS20150707.pdf](https://github.com/sul-dlss/sul_pub/files/926876/WoSWS20150707.pdf)

**Comment by peetucket** [comment]
I have a username/password combo we can use for the new API (will not post in ticket).  I have tested with a single query and it works.

**Comment by darrenleeweber** [comment]
The WoS temporary auth credential is available in shared_configs, see
- https://github.com/sul-dlss/shared_configs/tree/sul-pub-laptop

**Comment by darrenleeweber** [comment]
Peter's initial code to explore the new WoS API is in the `rialto-search` branch, i.e.
- https://github.com/sul-dlss/sul_pub/blob/rialto-search/bin/faculty_wos_search.rb
