### ISSUE TITLE
Create new Web of Science source record model(s) and corresponding database table(s)

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#184]
supercedes SciencewireSourceRecord

Needs to parse new doc result to doc-hash

and create the corresponding database for persistence

linked to #202

depends on #264

**Comment by darrenleeweber** [comment]
I've added commentary to #264 and proposed that a single source record could suffice to store the new WOS API data.  I'll proceed with that plan, unless we decide otherwise later.
