### ISSUE TITLE
Modify public APIs used by CAP to use new WoS harvester based on feature flags

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#189]
This is used by CAP for searching for pubs manually by DOI, WosID, title

**Comment by atz** [comment]
While we talked about more complex configurations, at this point the setting should be a boolean (default false) such that the code could be deployed to production and not change behavior (i.e. w/o shared_configs being updated yet).

**Comment by peetucket** [comment]
duplicates #408
