### ISSUE TITLE
Analysis: what to do with existing data from Sciencewire

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#201]
Keep existing pub_hash data and add to it or rebuild all pub_hashes?

Do we repull all publications ?  Or try and match up with existing?  Do we keep existing pub_hashes or rebuild?

**Comment by atz** [comment]
Basic look at non-internal tables:
```
mysql> select count(*) from author_identities;
14490

mysql> select count(*) from authors;
111606

mysql> select count(*) from batch_uploaded_source_records;
29941

mysql> select count(*) from contributions;
891387

mysql> select count(*) from publication_identifiers;
1239901

mysql> select count(*) from publications;
442083

mysql> select count(*) from pubmed_source_records;
258409

mysql> select count(*) from sciencewire_source_records;
393960

mysql> select count(*) from trash_records;
16890

mysql> select count(*) from user_submitted_source_records;
18643

mysql> select count(*) from versions;
0

```

So the question we have is about those `393960` ScienceWire records?

**Comment by peetucket** [comment]
Yes, exactly.  Those "_source_record" tables keep the records as we originally received them from that source API.  We then transform that source data (and throw away some of it) and store the results in various places (the publications table, the publication_identifiers table, the contributions table, etc.).  So when we switch to a new API, there will no longer be sciencewire source records, there will be web_of_science source records, and they will look totally different.  In theory, we can do a complete re-pull of all of those publications and get the new source format.  But we probably dont' want to trash the existing data because it is used on current profile pages, and we want to minimize disruptions.  So this ticket was to stimulate some discussion on how best to handle this transition.

**Comment by atz** [comment]
In the interests of analyzing some of that table then, here's a breakdown of the table by when records were created:
```
mysql> select * from (SELECT COUNT(id), DATE_FORMAT(created_at, '%Y-%m') as 'ym' from sciencewire_source_records GROUP BY YEAR(created_at), MONTH(created_at)) as foo ORDER BY ym;
+-----------+---------+
| COUNT(id) | ym      |
+-----------+---------+
|    167105 | 2013-06 |
|     65096 | 2013-07 |
|      4300 | 2013-08 |
|      6537 | 2013-09 |
|      7918 | 2013-10 |
|      3809 | 2013-11 |
|       799 | 2013-12 |
|      2946 | 2014-01 |
|      1560 | 2014-02 |
|      3070 | 2014-03 |
|      1244 | 2014-04 |
|      1010 | 2014-05 |
|      4918 | 2014-06 |
|      1451 | 2014-07 |
|      7493 | 2014-08 |
|      3047 | 2014-09 |
|      2185 | 2014-10 |
|      1022 | 2014-11 |
|       843 | 2014-12 |
|      1716 | 2015-01 |
|      2039 | 2015-02 |
|      1555 | 2015-03 |
|       729 | 2015-04 |
|     22304 | 2015-05 |
|      1288 | 2015-06 |
|      1479 | 2015-07 |
|      8134 | 2015-08 |
|      2829 | 2015-09 |
|      8982 | 2015-10 |
|      1327 | 2015-11 |
|       831 | 2015-12 |
|      1381 | 2016-01 |
|      3451 | 2016-02 |
|      6737 | 2016-03 |
|      2005 | 2016-04 |
|       969 | 2016-05 |
|      3078 | 2016-06 |
|      1777 | 2016-07 |
|       778 | 2016-08 |
|      3066 | 2016-09 |
|      1156 | 2016-10 |
|      2720 | 2016-11 |
|      1761 | 2016-12 |
|      3375 | 2017-01 |
|      1625 | 2017-02 |
|      1627 | 2017-03 |
|      2895 | 2017-04 |
|      6741 | 2017-05 |
|      2184 | 2017-06 |
|      4928 | 2017-07 |
|      1570 | 2017-08 |
|       577 | 2017-09 |
+-----------+---------+
52 rows in set (6.98 sec)
```
So more than half of the records were acquired in the first two months.  

I also note that only `278672` of `393960` sciencewire records have a (non-null) `pmid`.

**Comment by atz** [comment]
### OLD

The old ScienceWire docs suggest the availability of 3 "data sources":
- `PublicationCatalog`
- `GrantCatalog`
- `USPTOPatentCatalog`

We currently seem to use only the `PublicationCatalog`, which is fed from 5 upstream sources: -
- `SCIE`: Science Citation Index Expanded
- `SSCI`: Social Sciences Citation Index
- `AHCI`: Arts & Humanities Citation Index 
- `CPCI`: Conference Proceedings Citation Index 
- `MEDLINE`

### NEW

The "Web of Science Core Collection" (WOS) includes:
- **`SCI`: Science Citation Index Expanded**
- **`SSCI`: Social Sciences Citation Index**
- **`AHCI`: Arts & Humanities Citation Index**
- `ISTP`: Conference Proceedings Citation Index - Science
- `ISSHP`: Conference Proceedings Citation Index - Social Sciences
- `IC`: Index Chemicus
- `CCR`: Current Chemical Reactions
- `BSCI`: Book Citation Index - Science
- `BHCI`: Book Citation Index - Social Sciences and Humanities

(**matches in bold**)

So only 3 of the 5 components have structurally similar matches.  `CPCI` is now broken out between Science and Social Sciences and `MEDLINE` is a totally separate non-WOS "database".

**Comment by atz** [comment]
**NOTE**: `All WokSearch operations return a maximum of 100 records. The operations retrieve and citedReferencesRetrieve use the queryId from a previous search operation to return records beyond the 100-record limit.`

This limit does not appear to have been present in the old API.  This will require additional query logic.

**Comment by peetucket** [comment]
Yes, indeed there is a new limit of 100, so there is no some new logic when to the query.

**Comment by atz** [comment]
### OLD API
#### `MatchedPublicationItemIdsForAuthor` 
Takes POST including:
- Author name(s)
- At least one email address or one seed publication

Returns a list of IDs of publications that match.
 
#### `PublicationItems`
- Takes GET including a list of IDs in URL.
- Returns JSON or XML of "full publication records".

#### `PublicationQuery`
- Takes POST of an XML document containing the search criteria.  Returns a query id.
- Takes GET including a query ID (from previous POST response) and returns "full publication records".  

I can safely conclude that "full publication records" are our intended payload.  

My interpretation of mapping from old API to new is:
- `PublicationItems -> retrieveById`
- `PublicationQuery -> search`
- `MatchedPublicationItemIdsForAuthor -> search`: note, may require `cited/related` functionality if we are using the "seed publication" criterion.  

`search` takes a "User Query".  For WoS Core, that covers the Field Tags:
```
• AD=Address
• AU=Author  **
• CF=Conference
• CI=City
• CU=Country
• DO=DOI  **
• ED=Editor  **
• FG=Grant Number
• FO=Funding Agency
• FT=Funding Text
• GP=Group Author  **
• IS=ISSN/ISBN
• OG=Organization - Enhanced
• OO=Organization
• PS=Province/State
• PY=Year Published
• RID=ResearcherID  **
• SA=Street Address 
• SG=Suborganization 
• SO=Publication Name 
• SU=Research Area 
• TI=Title 
• TS=Topic 
• UT=Accession Number  **?
• WC=Web of Science Category 
• ZP=Zip/Postal Code
```
`**` are fields of interest for replacement querying.

**NOTE**: "E-mail Address" exists as a returned field in the data but is NOT listed as queryable.  Were we relying on that?

TODO: see how we were using `PublicationQuery`, make sure same fields are queryable.

**Comment by atz** [comment]
I find this note in a spec regarding `MatchedPublicationItemIdsForAuthor`:

> The ScienceWire API documentation does not include a 'Version' element within the 'Author' element.  When asked about this element, they say "... we essentially implemented a custom recommendation algorithm for Stanford to use, behind the MatchedPublicationItemIdsForAuthor API. Because that API is called elsewhere in TR, we did not simply want to overwrite the old algorithm with the new and thus this 'Version' flag essentially says 'use the new algorithm.' I believe if you make the call without the 'Version' value present, you will get recommendations via the old algorithm."

Almost certainly then this custom functionality will be unavailable in the WoS API.  It is unclear how we are to replace in CAP the ScienceWire internal functionality that was built for us.  A perfect 1:1 replacement may very well be impossible.

**Comment by darrenleeweber** [comment]
We discussed trying to identify the existing records that do or do not have a WoS-ID.  We have a script related to this issue, see
- https://github.com/sul-dlss/sul_pub/blob/master/script/missing_wos_ids.rb
