### ISSUE TITLE
Make DOI matching the first rule in matching logic

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/sul_pub#21]
_From @peetucket on February 16, 2016 22:10_

related to #15 

We do not currently match on DOI, which is an oversight.  We should match. In fact, it should be the first If statement in the match logic.  This will be particularly important for when we expand the harvest logic to other resources.  

For example if you looks SULPUBIDs (in prod) for 34410 and 323126, even though they have different SWIDs, they have the same DOI.  [EDIT BY Peter 5/23/2016] I don't see these two as having the same DOI

The use case is to avoid adding duplicates, which can arise in the scenario outlined by Grace on April 5, 2016 below.  Note this comment leads to a second need, the periodic sweeping of recently updated WoS records to remove medline dupes.

"Because Medline (aka PubMed) indexes articles before the entire issue is published, they tend to add articles earlier than the Web of Science.  When an article is indexed in the Web of Science, Thomson Reuters (TR) sometimes doesn't catch the fact that an article is already indexed in Medline right away.  So the first time we get a WoS citation, it may not include the Medline citation yet.  Later on the PubMedID (PMID) is added to the WoS record (but as we aren't pulling it again, i.e. updating existing records), we don't add the newly added PMID to our record.  As a bottom line, we have ended up with WoS records that lack the PMID, and also have duplicate Medline records for the same citation.  

What to do?  DOIs should be present in the vast majority of both WoS and Medline records.  So DOIs could be used to identify duplicates.   Because WoS records have links to citing information, they are the preferred record to keep, BUT the abstract could be coded Public (not restricted), as it is available in Medline.   If feasible, I think that we should retrieve a new copy of confirmed WoS records after they have been in the system for several months (maybe do quarterly?) and then use them to identify Medline dups that would subsequently be removed from profiles (using the DOI to search for dupes)."

_Copied from original issue: sul-dlss/sul-pub#83_

**Comment by mejackreed** [comment]
_From @lmcglohon on May 23, 2016 17:44_

- [ ] PublicationIdentifier model?  does that have the DOI linked to the publication?
- [ ] if not, we need a new DOI column on the publications model for querying against
- [ ] also, have to iterate all through publications and extract DOI from pub-hash

**Comment by mejackreed** [comment]
_From @peetucket on May 23, 2016 23:14_

Get the DOI from the pub-hash.  Perhaps there is a better way?

```
p=Publication.find(34410)
p.pub_hash[:identifier].each {|identifier| puts identifier[:id] if identifier[:type] == 'doi'} ; nil
```

**Comment by mejackreed** [comment]
_From @peetucket on May 23, 2016 23:27_

Here is an example of a dupe with the same DOI, but it is not clear to me how it got there.  One record has a provenance of "batch", the other has "sciencewire".  I presume the first was hand entered, but our record does not have a DOI, even though it shows on the cap profile:

https://profiles.stanford.edu/karen-casciotti?tab=publications

capProfleID=45761
pubIDs=232874 and 301937

```
author=Author.find_by(:cap_profile_id=>'45761')
pubs=author.publications.where(:title=>'Insights on the marine microbial nitrogen cycle from isotopic approaches to nitrification')
pubs[0].pub_hash[:provenance] # batch entry
pubs[1].pub_hash[:provenance] # sciencewire
pubs[0].pub_hash[:identifier]  # not much here
pubs[1].pub_hash[:identifier] # has the PMID, DOI, etc.
```

**Comment by atz** [comment]
Obsolete ticket.
