### ISSUE TITLE
Remediate existing data affected by inaccurate "Conference Proceeding Document" mapping

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/sul_pub#23]
_From @peetucket on March 30, 2016 23:41_

Related to the bug fix in #169 

Firstly, the document type mapping needs to be corrected and, secondly, the citation styles for those publications need to be corrected. Notice, therefore, that we already have a remediation script to do just that:

https://github.com/sul-dlss/sul-pub/blob/master/script/fix_sw_procs_marked_as_article.rb

Also, determine whether citation styles depend on the mapping of document type using the sul_doc_types that can be assigned to Publication.pub_hash[:type]

_Copied from original issue: sul-dlss/sul-pub#171_

**Comment by mejackreed** [comment]
_From @peetucket on March 30, 2016 23:43_

Initial code bug commit was `Sep 26, 2013` and the fix-up script commit was `Sep 27, 2013`.

- commit with typo in https://github.com/sul-dlss/sul-pub/commit/f84a46e0f0e27b3134775ff88fd30d890f5c518b
- fix up commit in https://github.com/sul-dlss/sul-pub/commit/b5c2e82104adec8f712036b5345bf7e0c2512864#diff-869d84540ae4655ab0f1a71318c7977c

There was a switch from checking DocumentTypeList to checking the DocumentCategory. The code/spec commit had a typo (Conference Proceedings Document) and the fix-up script did not (Conference Proceeding Document). So, it’s just a simple typo mistake.

The fix-up script only fixed the Conference Proceeding Document category mapping to inproceedings, it did not try to fix any other doc categories that were previously handed by https://github.com/sul-dlss/sul-pub/blob/f84a46e0f0e27b3134775ff88fd30d890f5c518b/app/models/sciencewire_source_record.rb#L249-L259

Not sure why the CAP team did not get any complaints about conference proceeding citations appearing in a form that is the same as journal articles. Looking at the PubHash code that does the citation generation [1], it seems (at first glance) like the doc-category is not important and the citation is built from a lot of other fields.
[1] https://github.com/sul-dlss/sul-pub/blob/master/app/models/pub_hash.rb

Looking at github search results for any use of the sul_doc_types [2], it appears they serve the purpose to unify the source record categories (types) into a SUL doc-type category and this value can be assigned to the Publication.pub_hash[:type] field.

[2] https://github.com/sul-dlss/sul-pub/search?utf8=%E2%9C%93&q=sul_doc_types

**Comment by mejackreed** [comment]
_From @darrenleeweber on March 31, 2016 0:50_

A useful search for `inproceedings` on github:
  - https://github.com/sul-dlss/sul-pub/search?p=4&q=inproceedings&utf8=%E2%9C%93

**Comment by mejackreed** [comment]
_From @lmcglohon on May 23, 2016 17:50_

Most of the work here is running the remediation script on a test database and ensuring data integrity is preserved and affected records are correctly updated.

There may be an existing migration.

**Comment by mejackreed** [comment]
_From @drh-stanford on June 1, 2016 21:45_

There's a remediation scriptie here: https://github.com/sul-dlss/sul-pub/blob/master/script/fix_sw_procs_marked_as_article.rb

it basically does this to matching publications

```
      h[:type] = Settings.sul_doc_types.inproceedings
      pub.pub_hash = h
      pub.sync_publication_hash_and_db
      pub.save
```

**Comment by mejackreed** [comment]
_From @darrenleeweber on June 1, 2016 22:28_

That's the script.  Note there is another way to batch the records, see
- https://github.com/sul-dlss/sul-pub/blob/master/script/merge_duplicate_authorship.rb#L102

**Comment by mejackreed** [comment]
_From @darrenleeweber on June 1, 2016 22:34_

Looking at the code in `PubHash#csl_doc`, there is nothing specific about handling an `inproceedings` doc-type any differently from an `article` doc-type.  The code seems to create the CSL doc-type using other fields than just the `type`.  This may explain why this bug never raised any problems with citation styling.

**Comment by mejackreed** [comment]
_From @drh-stanford on June 6, 2016 21:17_

I've run this on my laptop, and it corrects the `:type` data - a couple examples:

```
:documenttypes_sw:
- Proceedings Paper
:type: inproceedings
:documentcategory_sw: Conference Proceeding Document
```

and

```
:documenttypes_sw:
- Article
:type: inproceedings
:documentcategory_sw: Conference Proceeding Document
```

**Comment by mejackreed** [comment]
_From @drh-stanford on June 6, 2016 22:21_

So, the trial run changed 25k records out of 395k. It took about an hour to run on my laptop.

**Comment by drh-stanford** [comment]
I don't think the fix-it scriptie is working correctly.  The `SciencewireSourceRecord` model keys off of the `inproceedings` value in `convert_sw_publication_doc_to_hash` to set a `:conference` key in the `pub_hash`. This is not showing up in the data.

**Comment by drh-stanford** [comment]
I ran into an exception in the citation generation for the new fixer scriptie:

```
ERROR 2016-06-07 12:22:58 -0700[31750]: Problem with pub 157519: #<NoMethodError: undefined method `<<' for nil:NilClass>
ERROR 2016-06-07 12:22:58 -0700[31750]: /Users/drh/workspace/sul_pub/app/models/pub_hash.rb:153:in `csl_doc'
/Users/drh/workspace/sul_pub/app/models/pub_hash.rb:54:in `to_apa_citation'
/Users/drh/workspace/sul_pub/app/models/publication.rb:350:in `update_formatted_citations'
/Users/drh/workspace/sul_pub/app/models/publication.rb:198:in `sync_publication_hash_and_db'
/Users/drh/workspace/sul_pub/app/models/publication.rb:211:in `rebuild_pub_hash'
script/fix_sw_procs_marked_as_article.rb:12:in `fix'
script/fix_sw_procs_marked_as_article.rb:50:in `block (2 levels) in search'
```
