### ISSUE TITLE
Create new publication records

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#230]
- [ ] Confirm the new fields that are being returned are a superset of the current fields
- [ ] Are there fields that were combined or split?
- [x] Don't create duplicate publications in the Publications table - we can use any identifier in the result set to see if we already have the publication, i.e. it is considered a duplicate if two source records have the same WoS ID, PMID or DOI  --- analysis captured in #260

**Comment by darrenleeweber** [comment]
All we really need to know is whether we can populate the PubHash data to generate citations properly.  A detailed comparison of the old (ScienceWire) vs. new (WoS) records is not really important (IMO), unless you have a driving business purpose for this that involves going back to Clarivate to ask for something more.  However, I think we should first focus on whether we can populate PubHash fields to create citations.  We already have issues about how to populate data in the PubHash from the new WoS records.

**Comment by darrenleeweber** [comment]
I'm voting to close this issue as a wontfix-kinda thing or a duplicate of other stuff.

**Comment by peetucket** [comment]
other work captured in #265 and #274
