### ISSUE TITLE
Confirm the new WoS API meets the minimum requirements for our current use cases

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#231]
- [x] can query by name and institution and return many results
  - this is similar to the `search_by_name` query in #223 but without the dates
- [x] can query by name and institution and date range and return many results
  - this is working in the `search_by_name` query in #223 
- [x] can query by specific DOI and return a result
  - this is working in #242 and see https://github.com/sul-dlss/sul_pub/issues/231#issuecomment-334259351
- [x] can query by title and optionally a year and return many results
  - use fields `TI=Title` or even `TS=Topic` with field `PY=Year Published`
  - a generic `wos_queries.search("custom user query")` will enable this in #242
- [x] can query by PMID and return a result
  - the hit rate could be low, see https://github.com/sul-dlss/sul_pub/issues/231#issuecomment-334238008
- [x] can pass in a list of WosIDs and get back many records 
  - [x] can get PMIDs for WosIDs
    - probably yes, when they are available, see https://github.com/sul-dlss/sul_pub/issues/231#issuecomment-334313848
    - we might also need to use http://ipscience-help.thomsonreuters.com/LAMRService/WebServicesOverviewGroup/overview.html
      - see also https://github.com/rpritchett/wos-amr/blob/master/lookup_ids.py

**Comment by darrenleeweber** [comment]
A record for Russ Altman contains a WoS UID - `<UID>MEDLINE:24551397</UID>` - and it has some dynamic data fields that indicate this UID could be a PMID, i.e.
```xml
  <dynamic_data>
    <citation_related>
      <tc_list>
        <silo_tc coll_id="MEDLINE" local_count="0"/>
      </tc_list>
    </citation_related>
    <cluster_related>
      <identifiers>
        <identifier type="eissn" value="1942-597X"/>
        <identifier type="pmid" value="MEDLINE:24551397"/>
      </identifiers>
    </cluster_related>
  </dynamic_data>
```

**Comment by darrenleeweber** [comment]
Find a record with a PMID in the rails console:
```ruby
> pub_ids = PublicationIdentifier.select('DISTINCT publication_id').where(identifier_type: 'PMID').limit(1).first
=> #<PublicationIdentifier:0x005605437947c8 id: nil, publication_id: 1>
> Publication.find(pub_ids.publication_id).pmid
=> 10000166
```

**Comment by darrenleeweber** [comment]
WRT to the `DOI` search, the WoS API doc (ver 3.0, July 7, 2015) contains:


- p. 29, has `Data Citation Index` field `DO=DOI`
- p. 33 has `SciELO Citation Index` with the same field
- p. 34 has `Web of Science Core Collection` with the `DO=DOI` field
- p. 53 has a couple of things with a DOI field and xpath:
  - `Book Digital Object Identifier (DOI) .../dynamic_data/cluster_related/identifiers`
  - `Digital Object Identifier (DOI) .../dynamic_data/cluster_related/identifiers`

**Comment by darrenleeweber** [comment]
RE - Can we get PMIDs for WosIDs

First, let's retrieve a publication record by the WosID:
```ruby
wos_id = '000070953800034'
PublicationIdentifier.where(identifier_type: 'WosItemID', identifier_value: wos_id)
wos_client = WosClient.new(Settings.WOS.AUTH_CODE, :debug);
wos_queries = WosQueries.new(wos_client);
wos_queries.retrieve_by_id("WOS:#{wos_id}")
# that works
```
