### ISSUE TITLE
Update shared_config with new API keys

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#233]

**Comment by darrenleeweber** [comment]
- [x] sul-pub-prod
  - https://github.com/sul-dlss/shared_configs/commit/c0881256199f84fc5e19e1969bda932f796efa7d
- [x] sul-pub-stage
  - https://github.com/sul-dlss/shared_configs/commit/12a8dd0f0b83a0c2cce39eed15a1b8f3e1fb13e8

**Comment by darrenleeweber** [comment]
I want to close that ticket, but I’m not entirely sure what the definition of done is for that?  Does it include deploying the shared_configs or is that done in another issue?  Is that done automatically by puppet (or do we need a dev-ops ticket for that) or maybe it’s hooked up in the capistrano deploy?

**Comment by darrenleeweber** [comment]
There is an entry in puppet for the shared_configs branches, e.g.
- https://github.com/sul-dlss/puppet/blob/production/hieradata/node/sul-pub-dev.stanford.edu.eyaml#L16

However, that doesn't resolve whether or not puppet is doing any change detection and automatically updating the data from each branch.

**Comment by peetucket** [comment]
I don't think puppet is involved in updates, and I don't think that it is done automatically on deploys unless you use a deploy hook.  Could be wrong, worth checking in #software-developers channel.  FWIF, I don't think DLSS projects have a standard on if the shared_configs should update automatically with deploys -- some do and some don't and while it is usually good if it happens automatically there was a case during a patch party where it bit us.

 The readme on the shared_configs repo indicates how to do an update via rake: https://github.com/sul-dlss/shared_configs

**Comment by peetucket** [comment]
and it probably makes sense to update the configs on the server and then consider the ticket closed

**Comment by darrenleeweber** [comment]
The capistrano tasks do include the shared configs gem
- https://github.com/sul-dlss/sul_pub/blob/master/Capfile#L27

**Comment by peetucket** [comment]
they could just define the rake tasks though, i wouldn't assume it adds in the deploy hooks so that the tasks are automatically when deploys occur

**Comment by darrenleeweber** [comment]
Deployment for shared-configs, for each stage in `config/deploy/*.rb`:
- [ ] cap-dev
- [ ] cap-qa
- [ ] dev
- [ ] prod
- [ ] stage
