### ISSUE TITLE
Consolidate or replace use of time_ago_in_words

### ISSUE THREAD

**Issue by dazza-codes** [sul-dlss/sul_pub#238]
This is related to using the dotiw gem in various places where it may not be necessary.

This is an interesting argument for not using these methods from rails/dotiw at all
- https://rails-bestpractices.com/posts/2012/02/10/not-use-time_ago_in_words/

If the dotiw gem is used, can it be required in an initializer in one place?

**Comment by atz** [comment]
The blog post only applies when you have a client-side that includes javascript. Our ugly rake tasks do not.  

Initialization presumes were are inside a fully initialized Rails application, but usage in rake tasks may not align with that.
