### ISSUE TITLE
Update shared_config for authentication for Links AMR api

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#247]
Currently we have the base64 encoded version, but we also need the username/password for use with the Links AMR API.  Likely good idea to remove the existing auth token since it can be derived from the username/password by doing a ```Base64.encode64('username:password')```

Also requires changes to the auth the auth code is retrieved and sent to the WoS Client, see #252

**Comment by atz** [comment]
Alternatively, we could derive the username and password from the existing config, right?

**Comment by peetucket** [comment]
correct, though it you'd have to split on a colon after decoding
