### ISSUE TITLE
Enable Daniel's access to sul-pub systems

### ISSUE THREAD

**Issue by darrenleeweber** [sul-dlss/sul_pub#249]
See https://github.com/sul-dlss/operations-tasks/issues/1372

**Comment by darrenleeweber** [comment]
The work on puppet for https://github.com/sul-dlss/operations-tasks/issues/1372 is done, all that is left now is for @Maatary to confirm that it works.

**Comment by Maatary** [comment]
@darrenleeweber  How do I confirm, that, connecting to the Box ? what is the address ? Would you mind sending me the command ?
