### ISSUE TITLE
Analysis: do we have the fields that we currently use from Pubmed to merge into Sciencewire in the new WoS record?

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#257]
Prereq #256

After figuring out which fields we currently merge into the pub_hash from Pubmed, do we get these fields in the new WoS API?

- [x] ask Rob for some example merged records to see if there is extra metadata from MEDLINE in them
- [x] examine merged WoS/MEDLINE records, and see if there are metadata fields that appear to come from MEDLINE in there

**Comment by darrenleeweber** [comment]
See https://github.com/sul-dlss/sul_pub/issues/256#issuecomment-336584793 for notes about access to this data in the `MEDLINE` records from the new WoS API.  Basically, yes, it looks like the `MEDLINE` records have all the data we need.  (We also need analysis of some `WOS` records.)

**Comment by darrenleeweber** [comment]
See https://github.com/sul-dlss/sul_pub/issues/264#issuecomment-335582440 for an example `WOS` record (I have no idea whether it's a "merged" pubmed/medline record or not).  It has some subject headings (but they might be LCSH and not MeSH).  It does not have an abstract or any PMID values, so I don't even know if we could find this one on PubMed.  It might not be in PubMed, the following advanced search (and similar variants) find no hits
- https://www.ncbi.nlm.nih.gov/pubmed?term=(Challenges%20for%20intelligent%20systems%20in%20biology%5BTitle%5D)%20AND%20Altman%20R%5BAuthor%5D

**Comment by peetucket** [comment]
From Rob on 10/15/2017: ```... we don’t merge the PMID record into the WoS record.  If there is a record that is in both WoS and Medline, we only return the WoS version, and the WoS version does not include any Medline metadata content.  I think you will still need to make the call out to Medline to get the metadata from them. ```

**Comment by darrenleeweber** [comment]
So here's what we know:
- WoS `MEDLINE` records have all the data we need (without going to PubMed)
- WoS `WOS` records do not have the data we need and they don't have a `PMID`
  - we do not know how to retrieve related data from PubMed without a `PMID`
  - as I read what Rob says, we cannot get access to the associated WoS `MEDLINE` record
  - we still lack a specific set of `WOS:{UID}` values to investigate the data ourselves
- There has been some initial investigation of the option to use an additional linking API
  - the goal of using that linking API is to create a path from any `WOS` record to PubMed

**Comment by peetucket** [comment]
I believe that summary above is all correct.
