### ISSUE TITLE
Adjust WoS queries to use institution name already configured in settings

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#271]
The default institution of Stanford in the new WoS queries class (here: https://github.com/sul-dlss/sul_pub/blob/master/lib/wos_queries.rb#L158) is using a string instead of the value in the settings.yml file (here:  https://github.com/sul-dlss/sul_pub/blob/master/config/settings.yml#L58)

or it should expose an attr writer for a harvester or rake task to set that value using settings or user data

**Comment by atz** [comment]
Ideally, it takes the institution as an optional param in the initializer and defaults to the value in Settings.

**Comment by darrenleeweber** [comment]
Work on this is done in https://github.com/sul-dlss/sul_pub/pull/320 - actually using the settings should be moved to another issue when we come to coding the harvester (the setting is in the harvester settings).
