### ISSUE TITLE
Name queries in the WoS client should follow the same model used in Sciencewire Client

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#272]
When performing name searches during harvesting, we should follow the same model used in sciencewire searches

in the current sciencewire querying stack, there is a class (https://github.com/sul-dlss/sul_pub/blob/master/lib/science_wire/author_name.rb) that is used to construct a name query so that we get more comprehensive results than simply searching for "Last, First" ... it adds other common variants with just first initial or first middle, etc., e.g. instead of "Mangiafico, Peter" you will search on "Mangiafico, Peter A or Mangiafico P or Mangiafico PA"

**Comment by atz** [comment]
Ideally, we should literally use the same `ScienceWire::AuthorName`, amended or extended if necessary.

**Comment by darrenleeweber** [comment]
This is what it does now
- https://github.com/sul-dlss/sul_pub/blob/master/lib/wos_queries.rb#L150-L161

This was copied from Peter's initial gist on how to work with the new SOAP API.  I presume it was derived from the original ScienceWire code, but I'll double check details.
