### ISSUE TITLE
Analysis: PublicationIdentifiers Cleanup (Dups and Nulls)

### ISSUE THREAD

**Issue by atz** [sul-dlss/sul_pub#276]
Split off from #260.  Testing from `cap-qa`.

### DUPS
Here's the number of duplicate identifier values per type in our `publication_identifiers` table:
```
doi: 4010
isbn: 19
legacy_cap_pub_id: 0
pmc: 33
PMID: 635
PublicationItemID: 24
SULPubId: 0
WoSItemID: 13
```

Literally any ID type we didn't coin ourselves has dups.  This should have been prevented at the database level.  We already have an index over `["identifier_type", "identifier_value"]`, but it should have been made unique.  

### NULL ENTRIES

Additionally, we have null `identifier_value` fields for **1606** `doi` records (and **1845** `isbn` records).  Those entries should probably be deleted since they don't identify anything!  `identifier_value` should be required in the ActiveRecord model AND enforced at the DB level.

### Analysis

If we focus just on `PublicationItemID` and `WoSItemID` it seems like some cleanup could be achieved and then a model validation could prevent the future insertion of duplicates for those types.

#### Duplicate `PublicationItemID`s:
Appear 3x:
```
63914077
64134256
64264728
```
Appear 2x:
```
54049859
63754342
63848221
63855510
63914077
63926451
63930148
63943905
64031325
64046373
64059243
64101141
64105269
64128374
64134256
64264728
64271034
64379221
64382988
64502249
65502505
75359344
75615266
77361922
```
#### Duplicate `WosItemID`s:
Appear 3x:
```
000324326900005
000325809200002
000326220300026
```
Appear 2x:
```
000323240100001
000323783600005
000324084400006
000324125100059
000324233200001
000324326900005
000324693100003
000325395600085
000325809200002
000326061000008
000326220300026
000326305300008
000371581900021
```

**Comment by darrenleeweber** [comment]
Copying related commentary from slack:

Maybe double check the dup entries to see if some of the `DOI` or other dup fields also link to dup `Publication.id` values?  Might be useful to analyze the unique constraints on both `Publication` and `PublicationIdentifier` (looks like the latter doesn’t have any).

A long, long time ago, I had an ambitious thought about introducing foreign-key constraints, but that work was halted to focus on other stuff.
- https://github.com/sul-dlss/sul_pub/tree/foreign-key-immigration
- I didn’t entirely succeed in that ambitious effort

**Comment by atz** [comment]
There is also the issue of duplication of `identifier_uri` which also should have a uniqueness constraint.  

Example triplication (both value and URI):
```ruby
[#<PublicationIdentifier:0x00000055345ff8
  id: 938856,
  publication_id: 268884,
  identifier_type: "WoSItemID",
  identifier_value: "000325809200002",
  identifier_uri: "https://ws.isiknowledge.com/cps/openurl/service?url_ver=Z39.88-2004&rft_id=info:ut/000325809200002",
  certainty: "confirmed",
  created_at: Tue, 26 Nov 2013 02:27:49 UTC +00:00,
  updated_at: Sat, 06 May 2017 15:14:41 UTC +00:00>,
 #<PublicationIdentifier:0x00000055345e90
  id: 939364,
  publication_id: 269056,
  identifier_type: "WoSItemID",
  identifier_value: "000325809200002",
  identifier_uri: "https://ws.isiknowledge.com/cps/openurl/service?url_ver=Z39.88-2004&rft_id=info:ut/000325809200002",
  certainty: "confirmed",
  created_at: Tue, 26 Nov 2013 03:08:55 UTC +00:00,
  updated_at: Sat, 06 May 2017 15:15:31 UTC +00:00>,
 #<PublicationIdentifier:0x00000055345d28
  id: 940578,
  publication_id: 269524,
  identifier_type: "WoSItemID",
  identifier_value: "000325809200002",
  identifier_uri: "https://ws.isiknowledge.com/cps/openurl/service?url_ver=Z39.88-2004&rft_id=info:ut/000325809200002",
  certainty: "confirmed",
  created_at: Tue, 26 Nov 2013 05:25:25 UTC +00:00,
  updated_at: Sat, 06 May 2017 15:17:35 UTC +00:00>]
```

Note: 3 different publication records.  

Each of these is the article "A multicenter study to standardize reporting and analyses of fluorescence-activated cell-sorted murine intestinal epithelial cells" from 2013 with minor differences to the pub_hash (in `:identifier, :journal, :abstract, :last_updated, :authorship, :sulpubid, :mesh_headings`).  Example difference in `:journal`:
```
:url=>"https://dx.doi.org/10.1152/ajpgi.00481.2012"
vs.
:url=>"10.1152/ajpgi.00481.2012"
```
:\

**Comment by darrenleeweber** [comment]
Might be related to #8 also.

**Comment by darrenleeweber** [comment]
```ruby
wos_item_ids = PublicationIdentifier.where(identifier_type:"WosItemID");
wos_item_ids.map(&:identifier_value).inject(Hash.new(0)) { |h,e| h[e] += 1; h }.select { |_k,v| v > 1 }
```
