### ISSUE TITLE
Go through wiki to find commands that use Sciencewire classes, create new documentation and identify rake tasks as needed to use WoS client

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#302]
Go through https://github.com/sul-dlss/sul_pub/wiki

particularly https://github.com/sul-dlss/sul_pub/wiki/Useful-commands-for-common-tasks:-SW

and the new one for WoS:
https://github.com/sul-dlss/sul_pub/wiki/Useful-commands:-WoS

- [ ] find any commands listed there referencing Sciencewire and update to the corresponding Web of Science
- [x] be sure the WoS page is up to date
- [ ] find any rake tasks referenced there and update to use Web of Science classes

**Comment by darrenleeweber** [comment]
Note that https://github.com/sul-dlss/sul_pub/pull/733 could change some details for the WOS wiki notes.

**Comment by darrenleeweber** [comment]
Updated https://github.com/sul-dlss/sul_pub/wiki/Useful-commands:-WoS
