### ISSUE TITLE
Update to grape 1.x

### ISSUE THREAD

**Issue by dazza-codes** [sul-dlss/sul_pub#308]
See where we ran into problems with old Publication.pub_hash data after a grape 1.x upgrade in
- https://github.com/sul-dlss/sul_pub/pull/303
- had to revert the grape 1.x update from #280 in #307

See the upgrade notes in:
- https://github.com/ruby-grape/grape/blob/master/UPGRADING.md

Depends on #300

**Comment by darrenleeweber** [comment]
Some slack chat about this....

Joe Atzberger [12:15 PM] 
the thing we need to test is whether our `serialize :pub_hash, Hash` is expected to be able to coerce Hashie::Mash objects to Hashes… without having `Hashie::Mash`installed.

seems unlikely

my reading is that the docs on that seem to be saying you always get back an object of the type specified, but it seems to be looser than that; like `pub_hash.is_a? Hash` might be true, but the returned object could be anything extending Hash


Darren Weber [12:18 PM] 
I suppose somehow one of our model specs could use a serialized Hashie::Mash and test if the deserialized object responded to specific Hashie::Mash methods.  Feels nasty.  Might as well just check in spec_helper if Hashie::Mash is defined?  (Not spec_helper, cause that’s run every time, but you know…)
