### ISSUE TITLE
Come up with a design proposal for the WoS harvester

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#317]
consider generalization into a harvester that can work with multiple sources

**Comment by darrenleeweber** [comment]
Connected to #254

**Comment by darrenleeweber** [comment]
Related documents:
- https://docs.google.com/drawings/d/15hOFHC54KDeEHs-4L9i-Q3AQ9AgUeOP1z3caqSnXmvs/edit

**Comment by darrenleeweber** [comment]
A schematic of some elements involved in the harvest (doesn't entirely capture my thoughts on the process, but it helps a little to picture the elements and data flow through the system).

[sul_pub_data_flow.pdf](https://github.com/sul-dlss/sul_pub/files/1422706/sul_pub_data_flow.pdf)

**Comment by darrenleeweber** [comment]
I've made a quick sketch of a WOS harvester in
- https://github.com/sul-dlss/sul_pub/blob/wos-harvest/lib/web_of_science/harvester.rb
- If this first sketch is an OK first approximation, we might proceed with PR #333
