### ISSUE TITLE
Create two sub-classes from WoS::Record base class and implement to_pub_hash methods

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#350]
We need to parse the WoSRecord to create pub_hashes based on type of WoS record (MEDLINE vs WoS)

- [ ] add to_pub_hash method on the base_class
- [ ] override that method in the sub classes

**Comment by darrenleeweber** [comment]
I want to break this out into two issues to focus on each subclass. I'll leave this issue here and link to the new ones.

**Comment by darrenleeweber** [comment]
This could be closed (with no estimate on the work), replaced with #366, #367, #368
