### ISSUE TITLE
Review cap_cutover.rake for possible deletion

### ISSUE THREAD

**Issue by atz** [sul-dlss/sul_pub#356]
There is a fairly significant surface of code that exists only to service this seemingly obsolete rake file `cap_cutover.rake`, some of which already described itself as "very temporary"... several years ago.  Ideally, we can rid ourselves of it completely.  

Barring that, if there are individual tasks that are still presently useful, please identify them so we can: 
- know what is worth maintaining, and
- get rid of the rest.

**Comment by peetucket** [comment]
Recommend we keep this file, but add a comment to the top:
```# As of November 2017 these tasks have not knowingly been run since at least March 2016.  It is possible they can be removed completely at a future refactor.```

*Some specific task note*

Tasks that seem to be related to some one time cutover, unlikely to ever be called again, can be deprecated:
* `pull_pubmed_for_cap` 
* `pull_sw_for_cap`
* `ingest_authors`
* `create_pubs_from_cap`
* `create_pubs_from_delta`
* `ingest_man_pubs`
* `man_pubs_from_delta`
* `fix_man_pubs_authors`
* `overwrite_profile_ids`
*  `build_pubs`, `build_missing_pubs`, `build_delta_pubs`, `update_pubs`, `update_authors`, `build_missing_pubs_one_item` --- these ultimately call a method `cutover_sync_hash_and_db` on the `Publication` model, which I don't think we need anymore either (it has a comment suggesting it was a temporary method)

No longer needed, this functionality now exists in the `update_pubs` task in the `sul.rake` file:
* `rewrite_authorship`

**Comment by atz** [comment]
Deprecation is a formal communication to consumers of code about changing pattern.  But we are the consumers of rake tasks.  What are we trying to communicate?  I don't mind adding some comments, but it seems weird that we are treating the users' behaviors as unknowable when they are us.  Either we use the things those (untested, unmaintained) tasks provide or we don't.  

If we don't need `cutover_sync_hash_and_db`, then we also don't need those 6 rake tasks.

More concretely, when I look at these tasks, they spawn logs.  Those logs have 9 names:
```
cap_build_delta_pubs.log
cap_build_pubs.log
cap_create_pmid_pubs.log
cap_import_man_pubs.log
cap_import_pubmed_source_records.log
cap_import_sciencewire_source_records.log
cap_update_pubs.log
fix_man_pubs_authors.log
rebuild_authorship_in_hash.log
```
Our prod logs directory has files going back to `2016 Jun 1`.  NONE of those files appear.  

On `cap-qa`, the logs go further back to `2016 Apr 13` and still nothing.

So, based on evidence, it has been at least a year and a half since any of that code has been run, probably longer.  Some names are reused (two twice, one thrice), so that represents 13 different tasks that have not been run.  13 of 16 total tasks.  

The last major development was mid-2013 in the Willy Mene era.  

@peetucket Based on the criteria you described earlier, I contend that means we can delete those methods, right?

The only ones I haven't determined are deletable (because they only use `Rails.logger` and I haven't trolled our logs for evidence) are:
- `:overwrite_profile_ids` - `a very temporary, dangerous, and invasive procedure for creating qa machines for the School of Medicine testers`
- `:ingest_authors` - from CSV, apparently
- `:update_authors` - `utility to be used as needed for patches to records from csv file`

By my reading, `:overwrite_profile_ids` is toast, leaving only the questions of 2 methods:
1. Do you use any CSV features?
1. ... from `cap_cutover`?

**Comment by atz** [comment]
Consensus at standup today was to remove 14 of 16 methods and note deprecation of the remaining 2.

**Comment by peetucket** [comment]
I have never used `ingest_authors` and `update_authors` and am not sure there is a use case for when they would be used.

It would be useful if the commit/merge message that removes this functionality referenced the fact the bulk ingest of authors from CSV and other tasks related to a migration to sul-pub were removed (to make it easier to search back through the history in case we needed it again).

**Comment by darrenleeweber** [comment]
Opening this until the work is done to resolve it.  This is not just an analysis ticket, there is implementation work in #376 for instance.

**Comment by darrenleeweber** [comment]
@peetucket - #376 removes `find_issn_id_identifiers`.  It's not part of the analysis above.  It seems that it's not called anywhere else in the cutover rake tasks.  Is it useful or remove it also?

**Comment by peetucket** [comment]
i wasn't looking at methods, only at rake tasks, but if that method isn't called anywhere else, i don't see a reason to keep it
