### ISSUE TITLE
Create WebOfScience::WosRecord < WebOfScience::Record and do pub_hash_mapping for WoS Record

### ISSUE THREAD

**Issue by darrenleeweber** [sul-dlss/sul_pub#366]
From #350 
Depends #368 

- [ ] #368 implement `WebOfScience::Record#to_pub_hash` 
- [ ] `WebOfScience::WosRecord#to_pub_hash` must be something like
```ruby
def to_pub_hash
  super.merge {
    # WOS specific content mapping to pub_hash
  }
end
```

**Comment by peetucket** [comment]
see #401 regarding DOI/XREF_DOI

**Comment by darrenleeweber** [comment]
The class patterns are not going to be consistent with this initial proposal.  The details are falling out differently in https://github.com/sul-dlss/sul_pub/pull/379
