### ISSUE TITLE
Analysis: how to deal with two records from different databases with the same numerical identifier

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#371]
The WoS Client may return two records with the same numeric identifiers but different namespaces when searching multiple databases.

We may need to either:

- [ ] is the summary section the same between databases?  we may to parse differently depending on record
- [ ] change how we use and match up identifiers (e.g. not use the namespace?)
- [ ] do some searching through the resultset to remove dupes and specify an order of preference for deciding which records to keep (e.g. WoS, Medline, CCC, all else)

e.g.

```
bundle exec rake wos:publication['000288663100014']
bundle exec rake wos:publication['CCC:000288663100014']
bundle exec rake wos:publication['WOS:000288663100014']
```

**Comment by darrenleeweber** [comment]
Connected to #301

**Comment by atz** [comment]
I don't think there is anything to this ticket besides stuff represented elsewhere.  I.E., filter it out.

**Comment by peetucket** [comment]
We don't expect these to occur based on our subscription and they fill be filtered out if they do.
