### ISSUE TITLE
Construct PubHash "pages" values to match current Sciencewire format

### ISSUE THREAD

**Issue by darrenleeweber** [sul-dlss/sul_pub#383]
If the WOS record has pages information for `start` and `end` page, with the same page, it could map into the following in a PubHash pages field:
```ruby
:pages=>"413-413"
```
Is this the desired result or should it be simplified to one page, i.e.
```ruby
:pages=>"413"
```

In the google doc of the mappings at https://docs.google.com/document/d/1x5sZVpZ_nREWBizyiTCVuP6YmJ6-AhA2yfCxrWZi-FU/edit @Maatary notes that the prior format for SW-API records was like
```
:pages=>"413-6"
```
So, that's even more complex, esp. when the pages span boundaries across the 10-units, like `418-420` would be `418-20` in that form.

**Comment by peetucket** [comment]
Could matter for citation formatting

**Comment by darrenleeweber** [comment]
An example MEDLINE record has pages data where the end page is a truncated value already:
```xml
      <pub_info coverdate='2013' edate='2013-11-16' has_abstract='Y' medium='Internet' model='Electronic-eCollection' pubtype='Journal' pubyear='2013' sortdate='2013-01-01' vol='2013'>
        <page begin='1123' end='32'>1123-32</page>
      </pub_info>
```
