### ISSUE TITLE
Limit results to WoS and Medline editions only

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#419]
We are currently searching all databases using the WoK database identifier.  We want to limit results to only WoS and Medline results to prevent issues with parsing of other databases and potential duplication issues.  Clarivate tells us that using the <editions> filter does not work with limiting to specific databases.  Even though we only expect to get back WoS or MEDLINE records, we should filter against other types of records (e.g. CCC) just to be sure.

This could be a no-op -- if the code doesn't break when an unknown record is encountered, we could log this and ignore the record.  That is acceptable and this issue could then be closed. 

- [ ] can be done in the harvester/processor code (https://github.com/sul-dlss/sul_pub/blob/master/lib/web_of_science/process_records.rb)

**Comment by darrenleeweber** [comment]
The query class can be initialized with any database, see
- https://github.com/sul-dlss/sul_pub/blob/master/lib/web_of_science/queries.rb#L20-L23

**Comment by darrenleeweber** [comment]
Also, the WOS records class can group records by database, allowing us to filter them, see
- https://github.com/sul-dlss/sul_pub/blob/master/lib/web_of_science/records.rb#L32-L45
