### ISSUE TITLE
Remove unused and not working cap http client API call

### ISSUE THREAD

**Issue by darrenleeweber** [sul-dlss/sul_pub#458]
Double check what the CAP-API call is to get an author via sunetid?  We are getting back too many results for this query, e.g.
```
https://cap-dev.stanford.edu/cap-api/api/cap/v1/authors?uids=furmand
```

That authors API call should match the same result we get back from this call
```
https://cap-dev.stanford.edu/cap-api/api/cap/v1/authors/9957
```

**Comment by darrenleeweber** [comment]
These calls are in a ublic method on our CAP client, but it's never called, e.g.

```
$ git grep 'get_cap_profile_by_sunetid'
lib/cap_http_client.rb:54:  def get_cap_profile_by_sunetid(sunetid)
spec/lib/cap_http_client_spec.rb:41:  describe '#get_cap_profile_by_sunetid' do
spec/lib/cap_http_client_spec.rb:47:      subject.get_cap_profile_by_sunetid(12)
```
Looks like the app never calls this method, it should be deleted.

**Comment by peetucket** [comment]
reported to Tina
