### ISSUE TITLE
Investigate use of retries or other solution to auto retry if a throttle issue occurs with WoS API

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#518]
We don't expect to hit throttling limits with WoS API (https://github.com/sul-dlss/sul_pub/wiki/Web-of-Sciences-Expanded-API-Throttle-Limits) but if we do, it would be useful to have retries occur automatically.  

- [ ] can Savon gem be configured to retry 
- [ ] can we use retries gem?

**Comment by darrenleeweber** [comment]
This was partially addressed for one of the throttle limits that imposes 2500 queries per session by resetting the client session in https://github.com/sul-dlss/sul_pub/pull/576

**Comment by darrenleeweber** [comment]
There is an example of handling some exceptions and resetting authentication in:
- https://github.com/savonrb/savon/issues/371
