### ISSUE TITLE
Increase defaults for max_rows returned from ScienceWire

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/sul_pub#53]
_From @darrenleeweber on April 27, 2016 21:13_

The current default in science_wire_client is 200 publications.  A SQL query on prod-db indicates the ceiling for prolific authors is about 1200.  Perhaps we should increase the default for max_rows?

_Copied from original issue: sul-dlss/sul-pub#308_

**Comment by mejackreed** [comment]
_From @peetucket on May 4, 2016 22:29_

Does this mean we will not get back more than 200 publications for any given author on any given query?  So the authors who have more than this number entered them manually?

**Comment by mejackreed** [comment]
_From @darrenleeweber on May 5, 2016 0:59_

Yes, this means we can get back no more than 200 publications and they are sorted by the match rank.  So, for a dumb query on a prolific author, we may never get back all their publications.

**Comment by mejackreed** [comment]
_From @peetucket on May 5, 2016 18:54_

I will ask Tina and Grace to understand if there was some logic around this decision.  Perhaps there was a concern about too much bad data, but it does seem like an arbitrary limit that is easily exceeded by a prolific author, as you note.

**Comment by mejackreed** [comment]
_From @peetucket on May 5, 2016 22:48_

Possible historical reason was to minimize the noise.  Bottom line is that it should probably be increased, but only after some testing to be sure it doesn't produce too much noise.  Based on the fact that Tina has indicated there haven't been a lot of complaints of missing publications, I would not rate this a high priority now.

**Comment by mejackreed** [comment]
_From @darrenleeweber on May 6, 2016 16:9_

One interesting thought is that the dumb search could be limited to a set of results that is a little greater than the threshold used for the smart search.  So, when the smart search threshold is reached, the limit on the dumb search no longer applies.

However, our work on alt-names currently has no plan to use smart search for alt-names.  In this scenario, a prolific author who published most of their work using an alt-identity, will be impacted by this limit.

**Comment by atz** [comment]
Not relevant anymore as ScienceWire is being obsoleted.
