### ISSUE TITLE
Harvest alternate identity for all authors during WoS harvesting

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#573]
(AU=(Casciotti K OR Casciotti KL OR Casciotti Karen) AND OG=(Princeton University)) OR (AU=(Casciotti K OR Casciotti KL OR Casciotti Karen) AND OG=(Stanford University))

produces an equivalent result set to 

AU=(Casciotti K OR Casciotti KL OR Casciotti Karen) AND OG=(Princeton University OR Stanford University)

which is valid

So it appears the simpler form: 

(name OR name OR name) AND (institution OR institution OR institution) 

should work

**Comment by atz** [comment]
Note: a bunch of logic for `AuthorIdentity` is obsolete now that we have validations in place.  E.G., for a persisted record, `author_identity.first_name.present? && author_identity.last_name.present?` is tautological.
