### ISSUE TITLE
[sul_pub/production] Faraday::ClientError: the server responded with status 500

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/sul_pub#581]
## Backtrace

    line 53 of [PROJECT_ROOT]/lib/science_wire/request.rb: response
    line 25 of [PROJECT_ROOT]/lib/science_wire/request.rb: perform
    line 25 of [PROJECT_ROOT]/lib/science_wire/api/publication_query.rb: send_publication_query

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/50046/faults/35066843)

**Comment by darrenleeweber** [comment]
This could be a sign that the old SW-API is getting flaky prior to shutdown.

**Comment by peetucket** [comment]
There were times when the SW client was down, caught by okcomputer, I notified them and it came back.  Assume this was one of those times.
