### ISSUE TITLE
Delete unused rake tasks

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/sul_pub#59]
_From @drh-stanford on May 23, 2016 18:30_

Candidates are the `batch_import.rake`, `cap_cutover.rake`, `logging.rake`, and `sul.rake` in the `lib/tasks/` folder.

If we want to keep one-timer type scripties, perhaps put them all in a single `.rake` file, or make them `rails runner` scripties in `script/`

_Copied from original issue: sul-dlss/sul-pub#445_

**Comment by mejackreed** [comment]
_From @drh-stanford on May 26, 2016 19:41_

There's also the `ScienceWireHarvester.harvest_pubs_for_all_authors_parallel` rake task. That code is very confusing and arguably duplicative.

**Comment by atz** [comment]
Partially accomplished in 2017.
