### ISSUE TITLE
Update publication API to use WoS client for searching by title

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#604]
The "sourcelookup" method in the publications controller currently uses the ScienceWire client to search by title. We need to update this method and to use the Web of Science client instead.

Will require

- [ ] helper method to search Web of Science by title (possibly in queries class in web of science module)
- [ ] use of this new helper method in place of existing sciencewire helper method to search by title
- [ ] compare return structure from WoS API with return structure from sciencewire API for compatibility
- [ ] removal/updating of sources param in sourcelookup

**Comment by darrenleeweber** [comment]
See https://github.com/sul-dlss/sul_pub/blob/master/spec/lib/web_of_science/queries_spec.rb#L77-L80
That is:
```ruby
title = 'A research roadmap for next-generation sequencing informatics'
query = "TI=#{title}"
params = WebOfScience.queries.params_for_search(query)
records = WebOfScience.queries.search(params)
# then collect the record.pub_hash data from each record found and convert to JSON for an API response
```

**Comment by atz** [comment]
`PublicationsController#sourcelookup` now hits WOS for title, doi and pmid searches (when enabled).
