### ISSUE TITLE
Fix pending specs on author name spacing from PR #431

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/sul_pub#65]
_From @darrenleeweber on May 26, 2016 17:59_

PR #431 noted some extra spaces added to some author names in `PubHash#to_citation_data`; the specs contain pending items for this.  The bug is related to spec-data for authors that have no data provenance, so the author parsing attempts to work with data that contains variations derived from many data sources and the parser must make guesses about how to parse the name data.  It may be better to replace the spec-data with known data structures with known provenance.

_Copied from original issue: sul-dlss/sul-pub#469_

**Comment by darrenleeweber** [comment]
Fixed by #620
