### ISSUE TITLE
Alt-name queries may not be unique

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/sul_pub#67]
_From @darrenleeweber on May 31, 2016 6:4_

The alt-name code in the harvest broker does not detect unique variations in alt-names.  If there are duplicate name variations, it will run the same queries more than once.  The unique quality of a query depends on how an identity is used to generate a query.  A possible solution for this is to generate dumb-search queries for each alt-name and then de-dup an array of query xml.

_Copied from original issue: sul-dlss/sul-pub#490_

**Comment by peetucket** [comment]
no longer relevant for WoS API
