### ISSUE TITLE
Add in alerting for harvest job not run in the last 3 weeks

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#695]
By moving the symbolicTimeSpan parameter to only pull updates from the last 4 weeks when doing a scheduled harvest we run the risk of missing data if we don't harvest at least once every 4 weeks.  Since the harvest is scheduled bi-weekly, this should be ok unless a harvest fails to run for whatever reason (cron failure, server failure, etc.).  We should monitor the timestamp of the last successful harvest completion and alert if it is more than 3 weeks ago.

Ideas on how to do this:
1. Drop a timestamped file somewhere on the server when the bi-weekly harvest completes.
2. Add an ok-computer check that is monitored via nagios that checks the timestamp of that file and alerts if > 3 weeks from current check time.

or check WoS source record last time stamp in database

**Comment by atz** [comment]
Using 3 weeks as the interval for the check
