### ISSUE TITLE
SW-Harvester - order-specific bug in the specs

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/sul_pub#70]
_From @darrenleeweber on June 2, 2016 20:28_

There is an order-specific bug in the SW-Harvester specs.  It can be seen using:
```
RAILS_ENV=test bundle exec rspec --format documentation --seed 1924 ./spec/lib/science_wire_harvester_spec.rb
```

The errors point to `ScienceWireHarvester#harvest_pubs_for_author_ids`.

_Copied from original issue: sul-dlss/sul-pub#510_

**Comment by mejackreed** [comment]
_From @darrenleeweber on June 3, 2016 15:58_

Work on this could depend on #509.

**Comment by peetucket** [comment]
Do some analysis to determine if this is a test issue (i.e. having to do with test environment) or an actual bug somewhere in the code.

**Comment by darrenleeweber** [comment]
Replicated the errors in the current master branch.

**Comment by darrenleeweber** [comment]
Also confirmed that specs are passing when run in the defined order, i.e.
```
RAILS_ENV=test bundle exec rspec --order defined --format documentation ./spec/lib/science_wire_harvester_spec.rb
```
