### ISSUE TITLE
PubmedSourceRecord missing ValidYN attribute in CAP-QA

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/sul_pub#74]
_From @drh-stanford on June 6, 2016 20:57_

Reported by squash in the CAP-QA environment during the nightly `cap:poll`:

https://sul-squash-prod.stanford.edu/projects/cap/environments/cap-qa/bugs/4#history

Here is an example Author on which it failed: 

```
E, [2016-06-06T05:15:10.973745 #21451] ERROR -- : ScienceWireHarvester: Harvest failed for Author.find_by(id: 47525, cap_profile_id:
 93004)
```

_Copied from original issue: sul-dlss/sul-pub#521_

**Comment by darrenleeweber** [comment]
There is relevant code for this issue in
- https://github.com/sul-dlss/sul_pub/blob/master/app/models/pubmed_source_record.rb#L188

**Comment by drh-stanford** [comment]
See https://sul-squash-prod.stanford.edu/projects/sul-pub/environments/cap-qa/bugs/2
