### ISSUE TITLE
Investigate why journal identifier block in pub_hashes from WoS records is no longer an array

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#749]
Perform a title search for "Power spectrum for inflation models with quantum" on -prod and -cap-dev and look at the mapped results.  Note that the journal identifier block as has two entries in -prod (from sciencewire) and is an array, but only entry in -cap-dev (from WoS) and is not an array.  What is that?

`http://sul-pub-cap-dev.stanford.edu/publications/sourcelookup.json?title=Power spectrum for inflation models with quantum`

vs 

`http://sulcap.stanford.edu/publications/sourcelookup.json?title=Power spectrum for inflation models with quantum`

cap-dev (wos):

```    "title": "Power spectrum for inflation models with quantum and thermal noises",
      "journal": {
        "name": "JOURNAL OF COSMOLOGY AND ASTROPARTICLE PHYSICS",
        "issue": "3",
        "identifier": {
          "type": "issn",
          "id": "1475-7516",
          "url": "http://searchworks.stanford.edu/?search_field=advanced&number=1475-7516"
        }
      },
```

prod (sw):

``` 
      "journal": {
        "name": "JOURNAL OF COSMOLOGY AND ASTROPARTICLE PHYSICS",
        "issue": "3",
        "articlenumber": "032",
        "pages": "",
        "identifier": [
          {
            "type": "issn",
            "id": "1475-7516",
            "url": "http://searchworks.stanford.edu/?search_field=advanced&number=1475-7516"
          },
          {
            "type": "doi",
            "id": "10.1088/1475-7516/2013/03/032",
            "url": "https://dx.doi.org/10.1088/1475-7516/2013/03/032"
          }
        ]
      },
```

**Comment by peetucket** [comment]
Note that the Profiles team has amended their code to deal with this difference and be backwards compatible, but it would be good to understand what is happening.

**Comment by atz** [comment]
It appears to be here:
https://github.com/sul-dlss/sul_pub/blob/master/lib/web_of_science/map_citation.rb#L55

Effectively:
```ruby
j[:identifier] = rec.identifiers.pub_hash.find { |id| id[:type] == 'issn' } || 
                 rec.identifiers.pub_hash.find { |id| id[:type] == 'eissn' }
```

**Comment by atz** [comment]
@peetucket My interpretation is that the DOI applied to identification of the **journal** is incorrect.  In the example, the DOI identifies the **article** whereas the other IDs identify the serial.  I will proceed with fixing the structure and unless otherwise directed will not include article-level IDs from the journal `identifiers` array.
