### ISSUE TITLE
Document type mapping is not consistent between SW and WoS

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#754]
document type mappings should be the same from SW API to WoS API for the same publication

```https://sulcap-dev.stanford.edu/publications/sourcelookup?title=ESTIMATION OF THE AVERAGE WARFARIN MAINTENANCE DOSE IN SAUDI POPULATION```

produces for WOS:000267428100504

` "type": "article",`

```https://sulcap.stanford.edu/publications/sourcelookup?title=ESTIMATION OF THE AVERAGE WARFARIN MAINTENANCE DOSE IN SAUDI POPULATION```

produces for the same publication (happens to be SWID: 31814578 but same WOS ID):

`"type": "inproceedings",`

**Comment by atz** [comment]
### Sciencwire categorization

There is some bespoke code for processing bibtex files including an "`inproceeding` mode" [here](https://github.com/sul-dlss/sul_pub/blob/master/lib/science_wire_harvester.rb#L380-L396).  Other references exist in the `bibtex_ingester`.  Unsure if that is relevant to the older document.  

The remainder of references are in https://github.com/sul-dlss/sul_pub/blob/master/app/models/sciencewire_source_record.rb#L281-L292

The overall logic (condensed here):
```ruby
record_as_hash[:type] = (publication.xpath('DocumentCategory').text  == 'Conference Proceeding Document') ?
  Settings.sul_doc_types.inproceedings : 
  Settings.sul_doc_types.article
```
In effect, we collapse all SW documents to two types (with values from config).

**Comment by atz** [comment]
### WOS categorization

The similar logic for WOS is [here](https://github.com/sul-dlss/sul_pub/blob/master/lib/web_of_science/map_pub_hash.rb#L38-L50):
```ruby
        doc[:documentcategory_sw] = rec.pub_info['pubtype']
        doc[:type] = case rec.pub_info['pubtype']
                     when /conference/i
                       Settings.sul_doc_types.inproceedings
                     else
                       Settings.sul_doc_types.article
                     end
        doc
```
So previously we checked for `== 'Conference Proceeding Document'`.  Now we check for `/conference/i`.

**Comment by atz** [comment]
Fresh from WOS:
```ruby
WebOfScience.queries.user_query("TI=ESTIMATION OF THE AVERAGE WARFARIN MAINTENANCE DOSE IN SAUDI POPULATION").next_batch.to_a.first.pub_hash
=> {:author=>
  [{:display_name=>"Mirghani, R.", :first_name=>"R.", :last_name=>"Mirghani", :full_name=>"Mirghani, R.", :role=>"author"},
   {:display_name=>"Kashour, T.", :first_name=>"T.", :last_name=>"Kashour", :full_name=>"Kashour, T.", :role=>"author"}],
 :authorcount=>2,
 :publisher=>"WILEY-BLACKWELL PUBLISHING, INC",
 :city=>"MALDEN",
 :stateprovince=>"MA",
 :country=>"USA",
 :year=>"2009",
 :date=>"2009-08-01",
 :pages=>"135",
 :title=>"ESTIMATION OF THE AVERAGE WARFARIN MAINTENANCE DOSE IN SAUDI POPULATION",
 :journal=>
  {:name=>"BASIC & CLINICAL PHARMACOLOGY & TOXICOLOGY",
   :volume=>"105",
   :pages=>"135",
   :identifier=>{:type=>"issn", :id=>"1742-7835", :url=>"http://searchworks.stanford.edu/?search_field=advanced&number=1742-7835"}},
 :documenttypes_sw=>["Meeting Abstract", "Journal"],
 :documentcategory_sw=>"Journal",
 :type=>"article",
 :identifier=>
  [{:type=>"issn", :id=>"1742-7835", :url=>"http://searchworks.stanford.edu/?search_field=advanced&number=1742-7835"},
   {:type=>"WosItemID", :id=>"000267428100504", :url=>"https://ws.isiknowledge.com/cps/openurl/service?url_ver=Z39.88-2004&rft_id=info:ut/000267428100504"},
   {:type=>"WosUID", :id=>"WOS:000267428100504"}],
 :provenance=>"wos",
 :wos_uid=>"WOS:000267428100504",
 :issn=>"1742-7835",
 :wos_item_id=>"000267428100504",
 :apa_citation=>
  "Mirghani, R., &amp; Kashour, T. (2009). ESTIMATION OF THE AVERAGE WARFARIN MAINTENANCE DOSE IN SAUDI POPULATION. <i>BASIC &amp; CLINICAL PHARMACOLOGY &amp; TOXICOLOGY</i>, <i>105</i>, 135.",
 :mla_citation=>
  "Mirghani, R., and T. Kashour. “ESTIMATION OF THE AVERAGE WARFARIN MAINTENANCE DOSE IN SAUDI POPULATION.” <i>BASIC &amp; CLINICAL PHARMACOLOGY &amp; TOXICOLOGY</i> 105 (2009): 135. Print.",
 :chicago_citation=>
  "Mirghani, R., and T. Kashour. 2009. “ESTIMATION OF THE AVERAGE WARFARIN MAINTENANCE DOSE IN SAUDI POPULATION.” <i>BASIC &amp; CLINICAL PHARMACOLOGY &amp; TOXICOLOGY</i> 105. WILEY-BLACKWELL PUBLISHING, INC: 135."}
```

The important part seems to be:
```ruby
 :documenttypes_sw=>["Meeting Abstract", "Journal"],
 :documentcategory_sw=>"Journal",
 :type=>"article",
```

So maybe we need to include `Meeting Abstract` as `inproceeding`?  @peetucket can you confirm or redirect?  

The WOS code's test coverage inadedquate relative to its SW predecessor.

**Comment by atz** [comment]
There seems to be a second source of "doctype" data in the WOS records that might be preferable:
```xml
    <summary>
      ...
      <doctypes count='4'>
        <doctype>Journal Article</doctype>
        <doctype>Research Support, N.I.H., Extramural</doctype>
        <doctype>Research Support, Non-U.S. Gov't</doctype>
        <doctype>Research Support, U.S. Gov't, Non-P.H.S.</doctype>
      </doctypes>
    </summary>
    <fullrecord_metadata>
     ...
      <normalized_doctypes count='2'>
        <doctype>Article</doctype>
        <doctype>Other</doctype>
      </normalized_doctypes>
```
Example is a PubMed/MEDLINE record, so I don't know if it holds for all.  From grepping fixtures and cassettes, the values for `normalized_doctypes` include:
- `Article`
- `Letter`
- `Retraction`
- `Review`
- `Article`, `Other`

**Comment by atz** [comment]
### ScienceWire mapping revisited 

The logic is broader than first thought, according to this multi-val Setting:
```ruby
Settings.sw_doc_type_mappings.conference
=> ["Clinical Conference",
 "Congresses",
 "Consensus Development Conference",
 "Consensus Development Conference NIH",
 "Meeting Abstract",
 "Meeting Summary",
 "Meeting-Abstract",
 "Overall",
 "Proceedings Paper"]
```
There is a `SciencewireSourceRecord.lookup_sw_doc_type` method [here](https://github.com/sul-dlss/sul_pub/blob/master/app/models/sciencewire_source_record.rb#L269-L279) that does matching against all those settings values.  

The method appears to be entirely unused. 😠

**Comment by atz** [comment]
A regex that seems accurate enough and catches all 9 of those values is: 
`/\b(Meeting|Conference|Congresses|Overall|Proceeding)/i`

**Comment by atz** [comment]
### WOS mapping revisited

In the `pub_info` section, the WoS record in question **does** identify itself as having a `pub_type` of "Journal" only.   
```ruby
rec.doc.at('static_data/summary/pub_info')
=> #(Element:0x3fec90664614 {
  name = "pub_info",
  attributes = [
    #(Attr:0x3fec9065b12c { name = "sortdate", value = "2009-08-01" }),
    #(Attr:0x3fec9065b104 { name = "pubyear", value = "2009" }),
    #(Attr:0x3fec9065b0c8 { name = "has_abstract", value = "N" }),
    #(Attr:0x3fec9065b0b4 { name = "coverdate", value = "AUG 2009" }),
    #(Attr:0x3fec9065b08c { name = "pubmonth", value = "AUG" }),
    #(Attr:0x3fec9065b078 { name = "vol", value = "105" }),
    #(Attr:0x3fec9065b050 { name = "pubtype", value = "Journal" })],
  children = [
    #(Element:0x3fec906176d4 {
      name = "page",
      attributes = [ #(Attr:0x3fec90616b94 { name = "begin", value = "135" }), #(Attr:0x3fec90616b6c { name = "end", value = "135" }), #(Attr:0x3fec90616b58 { name = "page_count", value = "1" })],
      children = [ #(Text "135-135")]
      })]
  })
```
So that section is less valuable than `static_data/summary/doctypes/doctype`.
