### ISSUE TITLE
Coveralls isn't reporting correctly

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/sul_pub#81]
Currently showing that no runs have been made even though there have been PR's https://coveralls.io/github/sul-dlss/sul_pub

**Comment by drh-stanford** [comment]
Looked into this and our travis builds are not firing off the coveralls registration. The travis log should have something like this after the specs are run:

```
[Coveralls] Submitting to https://coveralls.io/api/v1
[Coveralls] Job #XXX
[Coveralls] https://coveralls.io/jobs/XXX
```
