### ISSUE TITLE
Some publications from WoS (provenance=sciencewire) are missing WoS IDs?

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#86]
Pointed out by Tina: Investigate missing WoS ID's for publications that come from WoS (provenance is sciencewire), but for some reason do not have the WoS id in the json.

**Comment by darrenleeweber** [comment]
There is no provenance `WoS`, it's only `sciencewire` (AFAIK).

**Comment by peetucket** [comment]
right, updated description.  Example record from Tina below:

sciencewire_id=42708914
sul_pub_id=64

I have confirmed this publication has no WoSID in the pub has or the identifiers table and it is not in the source record either:

```
p=Publication.find_by(:sciencewire_id=>'42708914')
puts p.pub_hash[:provenance]
# sciencewire
 puts p.pub_hash[:identifier]
# no WoSID
puts SciencewireSourceRecord.find_by(:sciencewire_id=>p.sciencewire_id).source_data
# no WoSID
p.publication_identifiers
# no WoSID
```

**Comment by peetucket** [comment]
Tina says this publication is not on the author's profile page either, which might be because the contribution status is unknown?  (probably has nothing to do with missing identifier)

```
p=Publication.find_by(:sciencewire_id=>'42708914')
p.authors  
# has two authors, one of which is Tina from a couple days ago, I assume she was testing adding it to he profile
p.contributions
# connected to the main author (Frank Longo) but with a status of "unknown", perhaps explaining why it is nowhere on his profile?  denied by Tina
```

**Comment by peetucket** [comment]
Request original record from ScienceWire, still don't see WoSID:

```
p=Publication.find_by(:sciencewire_id=>'42708914')
client=ScienceWireClient.new
client.get_full_sciencewire_pubs_for_sciencewire_ids(p.sciencewire_id.to_s)
```

**Comment by darrenleeweber** [comment]
The script in #108 did not find any `WoSItemID` in the source records for any of the 30,000+ publications without a `WoSItemID` in the pub_hash.  It seems safe to conclude that there is no bug in how we populate the publication identifiers for the `WoSItemID`.  (It also seems likely that these ScienceWire publications do not have a `WoSItemID`, even if they were to be harvested again.)

**Comment by darrenleeweber** [comment]
#108 has been updated to include a process for updating any SW publications without a WoSItemID value.  The script updated about 30,000 SW publications in the prod-db-dump on my laptop; about 5,000 of those have a new WoSItemID value.

**Comment by darrenleeweber** [comment]
I found a mongo query that can find these records:
```js
db.getCollection('publications').find({provenance: "sciencewire", "identifier.type": {$ne: "WoSItemID"} }).count()
```
