### ISSUE TITLE
Harvest publications from Pubmed Central by querying via name and institution

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#973]
Topline harvesting from Pubmed, similar to WoS.  Requested for FY 2019

- [x] The PubMed client needs to have the ability to query PubMed for publications by name and institution and return an array of results.
- [x] The PubMed harvester needs to be refactored and subclassed from the Base::Harvester class, and have the relevant methods added to perform regular harvests.
- [x] Move the PubMed harvester to a sub-folder to match WoS.
- [x] De-duplication code needs to be written and/or confirmed as working to ensure duplicate publications (i.e. same PMID) are not added when harvesting is performed using WoS and PMID.
- [x] Logging needs to be added for PubMed harvester.
- [x] New tests need to be written for PubMed harvesting.
- [x] Scheduling of regular Pubmed harvesting needs to be added to the cron jobs via the schedule.rb file (same as WoS regular harvesting).
- [x] We need to be hook into the Pubmed harvesting from the nightly cap author polling (where we harvest nightly when authors are added or changed) -- may want to create a new `do_harvest` method in `AuthorsPoller` class which encompasses both WoS and Pubmed and then call this method instead of the WoS only method when we are ready to harvest
- [ ] Update wiki pages with new rake tasks for harvesting
- [ ] Smoke test

Resources:
- [Pubmed API Documentation](https://www.ncbi.nlm.nih.gov/books/NBK25501/) 
- [Searching a database with API](https://www.ncbi.nlm.nih.gov/books/NBK25500/#chapter1.Searching_a_Database)
- [Query syntax](https://www.ncbi.nlm.nih.gov/books/NBK25499/)

Example search by name query for Pubmed (post):
```
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&retmode=xml&api_key=ACTUAL_API_KEY_HERE&field=author&term=Casciotti, Karen OR Casciotti, K
```

So we we can use the `Settings.PUBMED.BASE_URI` but need a new setting analogous to the `FETCH_PATH`, and then need to create a new query in `PubmedClient` to send the query above, which returns PMIDs, for which we can then get full records using the existing `.fetch_records_for_pmid_list` method in the client.

**Comment by justinlittman** [comment]
@peetucket Do we want to search by affiliation, so it would be something like `((Casciotti, Karen[Author]) OR Casciotti, K[Author]) AND Stanford[Affiliation]`.

See https://www.ncbi.nlm.nih.gov/books/NBK3827/#pubmedhelp.Affiliation_AD

**Comment by peetucket** [comment]
Yes, that is right, and it might be multiple institutions for users that have multiple alternate identities, so `((Casciotti, Karen[Author]) OR Casciotti, K[Author]) AND (Stanford[Affiliation] OR Princeton[Affiliation])` (analog in WoS is https://github.com/sul-dlss/sul_pub/blob/master/lib/web_of_science/query_author.rb#L59)

**Comment by peetucket** [comment]
I thought POSTing to this might do it, but it seems like the interpretation is a bit off:

```https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&retmode=xml&term=((Casciotti, Karen[Author]) OR (Casciotti, K[Author])) AND (Stanford[Affiliation] OR Princeton[Affiliation])```

it spits back results but it is not interpreting the first initial form right:

```<QueryTranslation>(Casciotti, Karen[Full Author Name] OR (Casciotti[All Fields] AND K[Author])) AND (Stanford[Affiliation] OR Princeton[Affiliation])</QueryTranslation>```


note you can leave off the `api_key` for simplicity when testing posts, we use it in the app to minimize the likelihood of getting throttled

**Comment by justinlittman** [comment]
Looks like what we want to do is: `https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&retmode=xml&api_key=aa7564b9158885601ebfd96ba829fb6e5a08&term=((Casciotti+Karen[Author])+OR+(Casciotti+K[Author])+AND+(Stanford[Affiliation]+OR+Princeton[Affiliation])`

which results in `<QueryTranslation>Casciotti, Karen[Full Author Name] OR Casciotti K[Author] AND (Stanford[Affiliation] OR Princeton[Affiliation])</QueryTranslation>`
